// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: cline/docs_index.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty, EmptyRequest } from "./common";

export interface PingRequest {
  serverUrl: string;
}

export interface PingResponse {
  connected: boolean;
  serverVersion: string;
}

export interface ListProjectsRequest {
  serverUrl: string;
}

export interface ProjectInfo {
  name: string;
  mountPath: string;
  totalChunks: number;
  status: string;
}

export interface ListProjectsResponse {
  projects: ProjectInfo[];
}

export interface ProjectStatsRequest {
  serverUrl: string;
  project: string;
}

export interface ProjectStatsResponse {
  project: string;
  totalChunks: number;
  filesIndexed: number;
  byFormat: { [key: string]: number };
}

export interface ProjectStatsResponse_ByFormatEntry {
  key: string;
  value: number;
}

export interface DocsIndexProjectRequest {
  serverUrl: string;
  project: string;
}

export interface DocsIndexProjectResponse {
  filesScanned: number;
  filesIndexed: number;
  filesFailed: number;
  chunksAdded: number;
  elapsedMs: number;
}

export interface IndexUrlRequest {
  serverUrl: string;
  project: string;
  url: string;
  depth: number;
  maxPages: number;
}

export interface IndexUrlResponse {
  project: string;
  seedUrl: string;
  pagesCrawled: number;
  chunksAdded: number;
}

export interface UploadFileRequest {
  serverUrl: string;
  project: string;
}

export interface UploadFileResponse {
  project: string;
  filename: string;
  path: string;
  size: number;
  status: string;
}

export interface SearchDocumentsRequest {
  serverUrl: string;
  project: string;
  query: string;
  topK: number;
}

export interface SearchResult {
  text: string;
  score: number;
  hybridScore: number;
  metadata: string;
}

export interface SearchDocumentsResponse {
  project: string;
  query: string;
  results: SearchResult[];
}

export interface DocsIndexTool {
  name: string;
  description: string;
}

export interface DocsIndexTools {
  tools: DocsIndexTool[];
}

export interface RegisterMcpRequest {
  serverUrl: string;
}

export interface UnregisterMcpRequest {
}

function createBasePingRequest(): PingRequest {
  return { serverUrl: "" };
}

export const PingRequest: MessageFns<PingRequest> = {
  encode(message: PingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
    };
  },

  toJSON(message: PingRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingRequest>, I>>(base?: I): PingRequest {
    return PingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingRequest>, I>>(object: I): PingRequest {
    const message = createBasePingRequest();
    message.serverUrl = object.serverUrl ?? "";
    return message;
  },
};

function createBasePingResponse(): PingResponse {
  return { connected: false, serverVersion: "" };
}

export const PingResponse: MessageFns<PingResponse> = {
  encode(message: PingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.connected !== false) {
      writer.uint32(8).bool(message.connected);
    }
    if (message.serverVersion !== "") {
      writer.uint32(18).string(message.serverVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.connected = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingResponse {
    return {
      connected: isSet(object.connected) ? globalThis.Boolean(object.connected) : false,
      serverVersion: isSet(object.serverVersion)
        ? globalThis.String(object.serverVersion)
        : isSet(object.server_version)
        ? globalThis.String(object.server_version)
        : "",
    };
  },

  toJSON(message: PingResponse): unknown {
    const obj: any = {};
    if (message.connected !== false) {
      obj.connected = message.connected;
    }
    if (message.serverVersion !== "") {
      obj.serverVersion = message.serverVersion;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingResponse>, I>>(base?: I): PingResponse {
    return PingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingResponse>, I>>(object: I): PingResponse {
    const message = createBasePingResponse();
    message.connected = object.connected ?? false;
    message.serverVersion = object.serverVersion ?? "";
    return message;
  },
};

function createBaseListProjectsRequest(): ListProjectsRequest {
  return { serverUrl: "" };
}

export const ListProjectsRequest: MessageFns<ListProjectsRequest> = {
  encode(message: ListProjectsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListProjectsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProjectsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListProjectsRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
    };
  },

  toJSON(message: ListProjectsRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListProjectsRequest>, I>>(base?: I): ListProjectsRequest {
    return ListProjectsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListProjectsRequest>, I>>(object: I): ListProjectsRequest {
    const message = createBaseListProjectsRequest();
    message.serverUrl = object.serverUrl ?? "";
    return message;
  },
};

function createBaseProjectInfo(): ProjectInfo {
  return { name: "", mountPath: "", totalChunks: 0, status: "" };
}

export const ProjectInfo: MessageFns<ProjectInfo> = {
  encode(message: ProjectInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.mountPath !== "") {
      writer.uint32(18).string(message.mountPath);
    }
    if (message.totalChunks !== 0) {
      writer.uint32(24).int32(message.totalChunks);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProjectInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProjectInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.mountPath = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalChunks = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProjectInfo {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      mountPath: isSet(object.mountPath)
        ? globalThis.String(object.mountPath)
        : isSet(object.mount_path)
        ? globalThis.String(object.mount_path)
        : "",
      totalChunks: isSet(object.totalChunks)
        ? globalThis.Number(object.totalChunks)
        : isSet(object.total_chunks)
        ? globalThis.Number(object.total_chunks)
        : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: ProjectInfo): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.mountPath !== "") {
      obj.mountPath = message.mountPath;
    }
    if (message.totalChunks !== 0) {
      obj.totalChunks = Math.round(message.totalChunks);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProjectInfo>, I>>(base?: I): ProjectInfo {
    return ProjectInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProjectInfo>, I>>(object: I): ProjectInfo {
    const message = createBaseProjectInfo();
    message.name = object.name ?? "";
    message.mountPath = object.mountPath ?? "";
    message.totalChunks = object.totalChunks ?? 0;
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseListProjectsResponse(): ListProjectsResponse {
  return { projects: [] };
}

export const ListProjectsResponse: MessageFns<ListProjectsResponse> = {
  encode(message: ListProjectsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.projects) {
      ProjectInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListProjectsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProjectsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.projects.push(ProjectInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListProjectsResponse {
    return {
      projects: globalThis.Array.isArray(object?.projects)
        ? object.projects.map((e: any) => ProjectInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListProjectsResponse): unknown {
    const obj: any = {};
    if (message.projects?.length) {
      obj.projects = message.projects.map((e) => ProjectInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListProjectsResponse>, I>>(base?: I): ListProjectsResponse {
    return ListProjectsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListProjectsResponse>, I>>(object: I): ListProjectsResponse {
    const message = createBaseListProjectsResponse();
    message.projects = object.projects?.map((e) => ProjectInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseProjectStatsRequest(): ProjectStatsRequest {
  return { serverUrl: "", project: "" };
}

export const ProjectStatsRequest: MessageFns<ProjectStatsRequest> = {
  encode(message: ProjectStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProjectStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProjectStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProjectStatsRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
    };
  },

  toJSON(message: ProjectStatsRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProjectStatsRequest>, I>>(base?: I): ProjectStatsRequest {
    return ProjectStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProjectStatsRequest>, I>>(object: I): ProjectStatsRequest {
    const message = createBaseProjectStatsRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.project = object.project ?? "";
    return message;
  },
};

function createBaseProjectStatsResponse(): ProjectStatsResponse {
  return { project: "", totalChunks: 0, filesIndexed: 0, byFormat: {} };
}

export const ProjectStatsResponse: MessageFns<ProjectStatsResponse> = {
  encode(message: ProjectStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.project !== "") {
      writer.uint32(10).string(message.project);
    }
    if (message.totalChunks !== 0) {
      writer.uint32(16).int32(message.totalChunks);
    }
    if (message.filesIndexed !== 0) {
      writer.uint32(24).int32(message.filesIndexed);
    }
    globalThis.Object.entries(message.byFormat).forEach(([key, value]: [string, number]) => {
      ProjectStatsResponse_ByFormatEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProjectStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProjectStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalChunks = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.filesIndexed = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = ProjectStatsResponse_ByFormatEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.byFormat[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProjectStatsResponse {
    return {
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      totalChunks: isSet(object.totalChunks)
        ? globalThis.Number(object.totalChunks)
        : isSet(object.total_chunks)
        ? globalThis.Number(object.total_chunks)
        : 0,
      filesIndexed: isSet(object.filesIndexed)
        ? globalThis.Number(object.filesIndexed)
        : isSet(object.files_indexed)
        ? globalThis.Number(object.files_indexed)
        : 0,
      byFormat: isObject(object.byFormat)
        ? (globalThis.Object.entries(object.byFormat) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : isObject(object.by_format)
        ? (globalThis.Object.entries(object.by_format) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ProjectStatsResponse): unknown {
    const obj: any = {};
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.totalChunks !== 0) {
      obj.totalChunks = Math.round(message.totalChunks);
    }
    if (message.filesIndexed !== 0) {
      obj.filesIndexed = Math.round(message.filesIndexed);
    }
    if (message.byFormat) {
      const entries = globalThis.Object.entries(message.byFormat) as [string, number][];
      if (entries.length > 0) {
        obj.byFormat = {};
        entries.forEach(([k, v]) => {
          obj.byFormat[k] = Math.round(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProjectStatsResponse>, I>>(base?: I): ProjectStatsResponse {
    return ProjectStatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProjectStatsResponse>, I>>(object: I): ProjectStatsResponse {
    const message = createBaseProjectStatsResponse();
    message.project = object.project ?? "";
    message.totalChunks = object.totalChunks ?? 0;
    message.filesIndexed = object.filesIndexed ?? 0;
    message.byFormat = (globalThis.Object.entries(object.byFormat ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseProjectStatsResponse_ByFormatEntry(): ProjectStatsResponse_ByFormatEntry {
  return { key: "", value: 0 };
}

export const ProjectStatsResponse_ByFormatEntry: MessageFns<ProjectStatsResponse_ByFormatEntry> = {
  encode(message: ProjectStatsResponse_ByFormatEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProjectStatsResponse_ByFormatEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProjectStatsResponse_ByFormatEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProjectStatsResponse_ByFormatEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: ProjectStatsResponse_ByFormatEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProjectStatsResponse_ByFormatEntry>, I>>(
    base?: I,
  ): ProjectStatsResponse_ByFormatEntry {
    return ProjectStatsResponse_ByFormatEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProjectStatsResponse_ByFormatEntry>, I>>(
    object: I,
  ): ProjectStatsResponse_ByFormatEntry {
    const message = createBaseProjectStatsResponse_ByFormatEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseDocsIndexProjectRequest(): DocsIndexProjectRequest {
  return { serverUrl: "", project: "" };
}

export const DocsIndexProjectRequest: MessageFns<DocsIndexProjectRequest> = {
  encode(message: DocsIndexProjectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocsIndexProjectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocsIndexProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocsIndexProjectRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
    };
  },

  toJSON(message: DocsIndexProjectRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocsIndexProjectRequest>, I>>(base?: I): DocsIndexProjectRequest {
    return DocsIndexProjectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocsIndexProjectRequest>, I>>(object: I): DocsIndexProjectRequest {
    const message = createBaseDocsIndexProjectRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.project = object.project ?? "";
    return message;
  },
};

function createBaseDocsIndexProjectResponse(): DocsIndexProjectResponse {
  return { filesScanned: 0, filesIndexed: 0, filesFailed: 0, chunksAdded: 0, elapsedMs: 0 };
}

export const DocsIndexProjectResponse: MessageFns<DocsIndexProjectResponse> = {
  encode(message: DocsIndexProjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filesScanned !== 0) {
      writer.uint32(8).int32(message.filesScanned);
    }
    if (message.filesIndexed !== 0) {
      writer.uint32(16).int32(message.filesIndexed);
    }
    if (message.filesFailed !== 0) {
      writer.uint32(24).int32(message.filesFailed);
    }
    if (message.chunksAdded !== 0) {
      writer.uint32(32).int32(message.chunksAdded);
    }
    if (message.elapsedMs !== 0) {
      writer.uint32(40).int32(message.elapsedMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocsIndexProjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocsIndexProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.filesScanned = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.filesIndexed = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.filesFailed = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.chunksAdded = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.elapsedMs = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocsIndexProjectResponse {
    return {
      filesScanned: isSet(object.filesScanned)
        ? globalThis.Number(object.filesScanned)
        : isSet(object.files_scanned)
        ? globalThis.Number(object.files_scanned)
        : 0,
      filesIndexed: isSet(object.filesIndexed)
        ? globalThis.Number(object.filesIndexed)
        : isSet(object.files_indexed)
        ? globalThis.Number(object.files_indexed)
        : 0,
      filesFailed: isSet(object.filesFailed)
        ? globalThis.Number(object.filesFailed)
        : isSet(object.files_failed)
        ? globalThis.Number(object.files_failed)
        : 0,
      chunksAdded: isSet(object.chunksAdded)
        ? globalThis.Number(object.chunksAdded)
        : isSet(object.chunks_added)
        ? globalThis.Number(object.chunks_added)
        : 0,
      elapsedMs: isSet(object.elapsedMs)
        ? globalThis.Number(object.elapsedMs)
        : isSet(object.elapsed_ms)
        ? globalThis.Number(object.elapsed_ms)
        : 0,
    };
  },

  toJSON(message: DocsIndexProjectResponse): unknown {
    const obj: any = {};
    if (message.filesScanned !== 0) {
      obj.filesScanned = Math.round(message.filesScanned);
    }
    if (message.filesIndexed !== 0) {
      obj.filesIndexed = Math.round(message.filesIndexed);
    }
    if (message.filesFailed !== 0) {
      obj.filesFailed = Math.round(message.filesFailed);
    }
    if (message.chunksAdded !== 0) {
      obj.chunksAdded = Math.round(message.chunksAdded);
    }
    if (message.elapsedMs !== 0) {
      obj.elapsedMs = Math.round(message.elapsedMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocsIndexProjectResponse>, I>>(base?: I): DocsIndexProjectResponse {
    return DocsIndexProjectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocsIndexProjectResponse>, I>>(object: I): DocsIndexProjectResponse {
    const message = createBaseDocsIndexProjectResponse();
    message.filesScanned = object.filesScanned ?? 0;
    message.filesIndexed = object.filesIndexed ?? 0;
    message.filesFailed = object.filesFailed ?? 0;
    message.chunksAdded = object.chunksAdded ?? 0;
    message.elapsedMs = object.elapsedMs ?? 0;
    return message;
  },
};

function createBaseIndexUrlRequest(): IndexUrlRequest {
  return { serverUrl: "", project: "", url: "", depth: 0, maxPages: 0 };
}

export const IndexUrlRequest: MessageFns<IndexUrlRequest> = {
  encode(message: IndexUrlRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    if (message.url !== "") {
      writer.uint32(26).string(message.url);
    }
    if (message.depth !== 0) {
      writer.uint32(32).int32(message.depth);
    }
    if (message.maxPages !== 0) {
      writer.uint32(40).int32(message.maxPages);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IndexUrlRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIndexUrlRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.depth = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.maxPages = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IndexUrlRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      depth: isSet(object.depth) ? globalThis.Number(object.depth) : 0,
      maxPages: isSet(object.maxPages)
        ? globalThis.Number(object.maxPages)
        : isSet(object.max_pages)
        ? globalThis.Number(object.max_pages)
        : 0,
    };
  },

  toJSON(message: IndexUrlRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.depth !== 0) {
      obj.depth = Math.round(message.depth);
    }
    if (message.maxPages !== 0) {
      obj.maxPages = Math.round(message.maxPages);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IndexUrlRequest>, I>>(base?: I): IndexUrlRequest {
    return IndexUrlRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IndexUrlRequest>, I>>(object: I): IndexUrlRequest {
    const message = createBaseIndexUrlRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.project = object.project ?? "";
    message.url = object.url ?? "";
    message.depth = object.depth ?? 0;
    message.maxPages = object.maxPages ?? 0;
    return message;
  },
};

function createBaseIndexUrlResponse(): IndexUrlResponse {
  return { project: "", seedUrl: "", pagesCrawled: 0, chunksAdded: 0 };
}

export const IndexUrlResponse: MessageFns<IndexUrlResponse> = {
  encode(message: IndexUrlResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.project !== "") {
      writer.uint32(10).string(message.project);
    }
    if (message.seedUrl !== "") {
      writer.uint32(18).string(message.seedUrl);
    }
    if (message.pagesCrawled !== 0) {
      writer.uint32(24).int32(message.pagesCrawled);
    }
    if (message.chunksAdded !== 0) {
      writer.uint32(32).int32(message.chunksAdded);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IndexUrlResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIndexUrlResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.seedUrl = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.pagesCrawled = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.chunksAdded = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IndexUrlResponse {
    return {
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      seedUrl: isSet(object.seedUrl)
        ? globalThis.String(object.seedUrl)
        : isSet(object.seed_url)
        ? globalThis.String(object.seed_url)
        : "",
      pagesCrawled: isSet(object.pagesCrawled)
        ? globalThis.Number(object.pagesCrawled)
        : isSet(object.pages_crawled)
        ? globalThis.Number(object.pages_crawled)
        : 0,
      chunksAdded: isSet(object.chunksAdded)
        ? globalThis.Number(object.chunksAdded)
        : isSet(object.chunks_added)
        ? globalThis.Number(object.chunks_added)
        : 0,
    };
  },

  toJSON(message: IndexUrlResponse): unknown {
    const obj: any = {};
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.seedUrl !== "") {
      obj.seedUrl = message.seedUrl;
    }
    if (message.pagesCrawled !== 0) {
      obj.pagesCrawled = Math.round(message.pagesCrawled);
    }
    if (message.chunksAdded !== 0) {
      obj.chunksAdded = Math.round(message.chunksAdded);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IndexUrlResponse>, I>>(base?: I): IndexUrlResponse {
    return IndexUrlResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IndexUrlResponse>, I>>(object: I): IndexUrlResponse {
    const message = createBaseIndexUrlResponse();
    message.project = object.project ?? "";
    message.seedUrl = object.seedUrl ?? "";
    message.pagesCrawled = object.pagesCrawled ?? 0;
    message.chunksAdded = object.chunksAdded ?? 0;
    return message;
  },
};

function createBaseUploadFileRequest(): UploadFileRequest {
  return { serverUrl: "", project: "" };
}

export const UploadFileRequest: MessageFns<UploadFileRequest> = {
  encode(message: UploadFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadFileRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
    };
  },

  toJSON(message: UploadFileRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadFileRequest>, I>>(base?: I): UploadFileRequest {
    return UploadFileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadFileRequest>, I>>(object: I): UploadFileRequest {
    const message = createBaseUploadFileRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.project = object.project ?? "";
    return message;
  },
};

function createBaseUploadFileResponse(): UploadFileResponse {
  return { project: "", filename: "", path: "", size: 0, status: "" };
}

export const UploadFileResponse: MessageFns<UploadFileResponse> = {
  encode(message: UploadFileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.project !== "") {
      writer.uint32(10).string(message.project);
    }
    if (message.filename !== "") {
      writer.uint32(18).string(message.filename);
    }
    if (message.path !== "") {
      writer.uint32(26).string(message.path);
    }
    if (message.size !== 0) {
      writer.uint32(32).int64(message.size);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadFileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadFileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.size = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadFileResponse {
    return {
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      filename: isSet(object.filename) ? globalThis.String(object.filename) : "",
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: UploadFileResponse): unknown {
    const obj: any = {};
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadFileResponse>, I>>(base?: I): UploadFileResponse {
    return UploadFileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadFileResponse>, I>>(object: I): UploadFileResponse {
    const message = createBaseUploadFileResponse();
    message.project = object.project ?? "";
    message.filename = object.filename ?? "";
    message.path = object.path ?? "";
    message.size = object.size ?? 0;
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseSearchDocumentsRequest(): SearchDocumentsRequest {
  return { serverUrl: "", project: "", query: "", topK: 0 };
}

export const SearchDocumentsRequest: MessageFns<SearchDocumentsRequest> = {
  encode(message: SearchDocumentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    if (message.query !== "") {
      writer.uint32(26).string(message.query);
    }
    if (message.topK !== 0) {
      writer.uint32(32).int32(message.topK);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchDocumentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchDocumentsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.topK = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchDocumentsRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      topK: isSet(object.topK)
        ? globalThis.Number(object.topK)
        : isSet(object.top_k)
        ? globalThis.Number(object.top_k)
        : 0,
    };
  },

  toJSON(message: SearchDocumentsRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.topK !== 0) {
      obj.topK = Math.round(message.topK);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchDocumentsRequest>, I>>(base?: I): SearchDocumentsRequest {
    return SearchDocumentsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchDocumentsRequest>, I>>(object: I): SearchDocumentsRequest {
    const message = createBaseSearchDocumentsRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.project = object.project ?? "";
    message.query = object.query ?? "";
    message.topK = object.topK ?? 0;
    return message;
  },
};

function createBaseSearchResult(): SearchResult {
  return { text: "", score: 0, hybridScore: 0, metadata: "" };
}

export const SearchResult: MessageFns<SearchResult> = {
  encode(message: SearchResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.score !== 0) {
      writer.uint32(17).double(message.score);
    }
    if (message.hybridScore !== 0) {
      writer.uint32(25).double(message.hybridScore);
    }
    if (message.metadata !== "") {
      writer.uint32(34).string(message.metadata);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.score = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.hybridScore = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.metadata = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchResult {
    return {
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      score: isSet(object.score) ? globalThis.Number(object.score) : 0,
      hybridScore: isSet(object.hybridScore)
        ? globalThis.Number(object.hybridScore)
        : isSet(object.hybrid_score)
        ? globalThis.Number(object.hybrid_score)
        : 0,
      metadata: isSet(object.metadata) ? globalThis.String(object.metadata) : "",
    };
  },

  toJSON(message: SearchResult): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.score !== 0) {
      obj.score = message.score;
    }
    if (message.hybridScore !== 0) {
      obj.hybridScore = message.hybridScore;
    }
    if (message.metadata !== "") {
      obj.metadata = message.metadata;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchResult>, I>>(base?: I): SearchResult {
    return SearchResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchResult>, I>>(object: I): SearchResult {
    const message = createBaseSearchResult();
    message.text = object.text ?? "";
    message.score = object.score ?? 0;
    message.hybridScore = object.hybridScore ?? 0;
    message.metadata = object.metadata ?? "";
    return message;
  },
};

function createBaseSearchDocumentsResponse(): SearchDocumentsResponse {
  return { project: "", query: "", results: [] };
}

export const SearchDocumentsResponse: MessageFns<SearchDocumentsResponse> = {
  encode(message: SearchDocumentsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.project !== "") {
      writer.uint32(10).string(message.project);
    }
    if (message.query !== "") {
      writer.uint32(18).string(message.query);
    }
    for (const v of message.results) {
      SearchResult.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchDocumentsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchDocumentsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.results.push(SearchResult.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchDocumentsResponse {
    return {
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => SearchResult.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SearchDocumentsResponse): unknown {
    const obj: any = {};
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.results?.length) {
      obj.results = message.results.map((e) => SearchResult.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchDocumentsResponse>, I>>(base?: I): SearchDocumentsResponse {
    return SearchDocumentsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchDocumentsResponse>, I>>(object: I): SearchDocumentsResponse {
    const message = createBaseSearchDocumentsResponse();
    message.project = object.project ?? "";
    message.query = object.query ?? "";
    message.results = object.results?.map((e) => SearchResult.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDocsIndexTool(): DocsIndexTool {
  return { name: "", description: "" };
}

export const DocsIndexTool: MessageFns<DocsIndexTool> = {
  encode(message: DocsIndexTool, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocsIndexTool {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocsIndexTool();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocsIndexTool {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: DocsIndexTool): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocsIndexTool>, I>>(base?: I): DocsIndexTool {
    return DocsIndexTool.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocsIndexTool>, I>>(object: I): DocsIndexTool {
    const message = createBaseDocsIndexTool();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseDocsIndexTools(): DocsIndexTools {
  return { tools: [] };
}

export const DocsIndexTools: MessageFns<DocsIndexTools> = {
  encode(message: DocsIndexTools, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tools) {
      DocsIndexTool.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocsIndexTools {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocsIndexTools();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tools.push(DocsIndexTool.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocsIndexTools {
    return {
      tools: globalThis.Array.isArray(object?.tools) ? object.tools.map((e: any) => DocsIndexTool.fromJSON(e)) : [],
    };
  },

  toJSON(message: DocsIndexTools): unknown {
    const obj: any = {};
    if (message.tools?.length) {
      obj.tools = message.tools.map((e) => DocsIndexTool.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocsIndexTools>, I>>(base?: I): DocsIndexTools {
    return DocsIndexTools.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocsIndexTools>, I>>(object: I): DocsIndexTools {
    const message = createBaseDocsIndexTools();
    message.tools = object.tools?.map((e) => DocsIndexTool.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRegisterMcpRequest(): RegisterMcpRequest {
  return { serverUrl: "" };
}

export const RegisterMcpRequest: MessageFns<RegisterMcpRequest> = {
  encode(message: RegisterMcpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterMcpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterMcpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterMcpRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
    };
  },

  toJSON(message: RegisterMcpRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterMcpRequest>, I>>(base?: I): RegisterMcpRequest {
    return RegisterMcpRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterMcpRequest>, I>>(object: I): RegisterMcpRequest {
    const message = createBaseRegisterMcpRequest();
    message.serverUrl = object.serverUrl ?? "";
    return message;
  },
};

function createBaseUnregisterMcpRequest(): UnregisterMcpRequest {
  return {};
}

export const UnregisterMcpRequest: MessageFns<UnregisterMcpRequest> = {
  encode(_: UnregisterMcpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnregisterMcpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnregisterMcpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): UnregisterMcpRequest {
    return {};
  },

  toJSON(_: UnregisterMcpRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<UnregisterMcpRequest>, I>>(base?: I): UnregisterMcpRequest {
    return UnregisterMcpRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnregisterMcpRequest>, I>>(_: I): UnregisterMcpRequest {
    const message = createBaseUnregisterMcpRequest();
    return message;
  },
};

export type DocsIndexServiceDefinition = typeof DocsIndexServiceDefinition;
export const DocsIndexServiceDefinition = {
  name: "DocsIndexService",
  fullName: "cline.DocsIndexService",
  methods: {
    ping: {
      name: "ping",
      requestType: PingRequest as typeof PingRequest,
      requestStream: false,
      responseType: PingResponse as typeof PingResponse,
      responseStream: false,
      options: {},
    },
    listProjects: {
      name: "listProjects",
      requestType: ListProjectsRequest as typeof ListProjectsRequest,
      requestStream: false,
      responseType: ListProjectsResponse as typeof ListProjectsResponse,
      responseStream: false,
      options: {},
    },
    projectStats: {
      name: "projectStats",
      requestType: ProjectStatsRequest as typeof ProjectStatsRequest,
      requestStream: false,
      responseType: ProjectStatsResponse as typeof ProjectStatsResponse,
      responseStream: false,
      options: {},
    },
    indexDocsProject: {
      name: "indexDocsProject",
      requestType: DocsIndexProjectRequest as typeof DocsIndexProjectRequest,
      requestStream: false,
      responseType: DocsIndexProjectResponse as typeof DocsIndexProjectResponse,
      responseStream: false,
      options: {},
    },
    indexUrl: {
      name: "indexUrl",
      requestType: IndexUrlRequest as typeof IndexUrlRequest,
      requestStream: false,
      responseType: IndexUrlResponse as typeof IndexUrlResponse,
      responseStream: false,
      options: {},
    },
    uploadFile: {
      name: "uploadFile",
      requestType: UploadFileRequest as typeof UploadFileRequest,
      requestStream: false,
      responseType: UploadFileResponse as typeof UploadFileResponse,
      responseStream: false,
      options: {},
    },
    searchDocuments: {
      name: "searchDocuments",
      requestType: SearchDocumentsRequest as typeof SearchDocumentsRequest,
      requestStream: false,
      responseType: SearchDocumentsResponse as typeof SearchDocumentsResponse,
      responseStream: false,
      options: {},
    },
    listDocsIndexTools: {
      name: "listDocsIndexTools",
      requestType: EmptyRequest as typeof EmptyRequest,
      requestStream: false,
      responseType: DocsIndexTools as typeof DocsIndexTools,
      responseStream: false,
      options: {},
    },
    registerMcpServer: {
      name: "registerMcpServer",
      requestType: RegisterMcpRequest as typeof RegisterMcpRequest,
      requestStream: false,
      responseType: Empty as typeof Empty,
      responseStream: false,
      options: {},
    },
    unregisterMcpServer: {
      name: "unregisterMcpServer",
      requestType: UnregisterMcpRequest as typeof UnregisterMcpRequest,
      requestStream: false,
      responseType: Empty as typeof Empty,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
