// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: cline/docs_index.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty, EmptyRequest } from "./common";

export interface PingRequest {
  serverUrl: string;
}

export interface PingResponse {
  connected: boolean;
  serverVersion: string;
}

export interface ListProjectsRequest {
  serverUrl: string;
}

export interface ProjectInfo {
  name: string;
}

export interface ListProjectsResponse {
  projects: ProjectInfo[];
}

export interface IndexUrlRequest {
  serverUrl: string;
  project: string;
  url: string;
}

export interface IndexUrlResponse {
  taskId: string;
  project: string;
  status: string;
}

export interface UploadFileRequest {
  serverUrl: string;
  project: string;
}

export interface UploadFileResponse {
  taskId: string;
  project: string;
  status: string;
}

export interface SearchDocumentsRequest {
  serverUrl: string;
  project: string;
  query: string;
  topK: number;
}

export interface SearchResult {
  score: number;
  docId: string;
  sourceName: string;
  page: number;
  chunkIndex: number;
  text: string;
}

export interface SearchDocumentsResponse {
  project: string;
  query: string;
  results: SearchResult[];
}

export interface DocsIndexTool {
  name: string;
  description: string;
}

export interface DocsIndexTools {
  tools: DocsIndexTool[];
}

export interface RegisterMcpRequest {
  serverUrl: string;
}

export interface UnregisterMcpRequest {
}

export interface CreateProjectRequest {
  serverUrl: string;
  name: string;
}

export interface CreateProjectResponse {
  project: string;
  status: string;
}

export interface DeleteDocumentRequest {
  serverUrl: string;
  project: string;
  source: string;
}

export interface DeleteDocumentResponse {
  status: string;
}

export interface TaskStatusRequest {
  serverUrl: string;
  taskId: string;
}

export interface TaskStatusResponse {
  id: string;
  project: string;
  status: string;
  progress: number;
  message: string;
  detail: string;
}

function createBasePingRequest(): PingRequest {
  return { serverUrl: "" };
}

export const PingRequest: MessageFns<PingRequest> = {
  encode(message: PingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
    };
  },

  toJSON(message: PingRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingRequest>, I>>(base?: I): PingRequest {
    return PingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingRequest>, I>>(object: I): PingRequest {
    const message = createBasePingRequest();
    message.serverUrl = object.serverUrl ?? "";
    return message;
  },
};

function createBasePingResponse(): PingResponse {
  return { connected: false, serverVersion: "" };
}

export const PingResponse: MessageFns<PingResponse> = {
  encode(message: PingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.connected !== false) {
      writer.uint32(8).bool(message.connected);
    }
    if (message.serverVersion !== "") {
      writer.uint32(18).string(message.serverVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.connected = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingResponse {
    return {
      connected: isSet(object.connected) ? globalThis.Boolean(object.connected) : false,
      serverVersion: isSet(object.serverVersion)
        ? globalThis.String(object.serverVersion)
        : isSet(object.server_version)
        ? globalThis.String(object.server_version)
        : "",
    };
  },

  toJSON(message: PingResponse): unknown {
    const obj: any = {};
    if (message.connected !== false) {
      obj.connected = message.connected;
    }
    if (message.serverVersion !== "") {
      obj.serverVersion = message.serverVersion;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingResponse>, I>>(base?: I): PingResponse {
    return PingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingResponse>, I>>(object: I): PingResponse {
    const message = createBasePingResponse();
    message.connected = object.connected ?? false;
    message.serverVersion = object.serverVersion ?? "";
    return message;
  },
};

function createBaseListProjectsRequest(): ListProjectsRequest {
  return { serverUrl: "" };
}

export const ListProjectsRequest: MessageFns<ListProjectsRequest> = {
  encode(message: ListProjectsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListProjectsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProjectsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListProjectsRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
    };
  },

  toJSON(message: ListProjectsRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListProjectsRequest>, I>>(base?: I): ListProjectsRequest {
    return ListProjectsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListProjectsRequest>, I>>(object: I): ListProjectsRequest {
    const message = createBaseListProjectsRequest();
    message.serverUrl = object.serverUrl ?? "";
    return message;
  },
};

function createBaseProjectInfo(): ProjectInfo {
  return { name: "" };
}

export const ProjectInfo: MessageFns<ProjectInfo> = {
  encode(message: ProjectInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProjectInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProjectInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProjectInfo {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: ProjectInfo): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProjectInfo>, I>>(base?: I): ProjectInfo {
    return ProjectInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProjectInfo>, I>>(object: I): ProjectInfo {
    const message = createBaseProjectInfo();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseListProjectsResponse(): ListProjectsResponse {
  return { projects: [] };
}

export const ListProjectsResponse: MessageFns<ListProjectsResponse> = {
  encode(message: ListProjectsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.projects) {
      ProjectInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListProjectsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProjectsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.projects.push(ProjectInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListProjectsResponse {
    return {
      projects: globalThis.Array.isArray(object?.projects)
        ? object.projects.map((e: any) => ProjectInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListProjectsResponse): unknown {
    const obj: any = {};
    if (message.projects?.length) {
      obj.projects = message.projects.map((e) => ProjectInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListProjectsResponse>, I>>(base?: I): ListProjectsResponse {
    return ListProjectsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListProjectsResponse>, I>>(object: I): ListProjectsResponse {
    const message = createBaseListProjectsResponse();
    message.projects = object.projects?.map((e) => ProjectInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseIndexUrlRequest(): IndexUrlRequest {
  return { serverUrl: "", project: "", url: "" };
}

export const IndexUrlRequest: MessageFns<IndexUrlRequest> = {
  encode(message: IndexUrlRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    if (message.url !== "") {
      writer.uint32(26).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IndexUrlRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIndexUrlRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IndexUrlRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
    };
  },

  toJSON(message: IndexUrlRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IndexUrlRequest>, I>>(base?: I): IndexUrlRequest {
    return IndexUrlRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IndexUrlRequest>, I>>(object: I): IndexUrlRequest {
    const message = createBaseIndexUrlRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.project = object.project ?? "";
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseIndexUrlResponse(): IndexUrlResponse {
  return { taskId: "", project: "", status: "" };
}

export const IndexUrlResponse: MessageFns<IndexUrlResponse> = {
  encode(message: IndexUrlResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IndexUrlResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIndexUrlResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IndexUrlResponse {
    return {
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: IndexUrlResponse): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IndexUrlResponse>, I>>(base?: I): IndexUrlResponse {
    return IndexUrlResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IndexUrlResponse>, I>>(object: I): IndexUrlResponse {
    const message = createBaseIndexUrlResponse();
    message.taskId = object.taskId ?? "";
    message.project = object.project ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseUploadFileRequest(): UploadFileRequest {
  return { serverUrl: "", project: "" };
}

export const UploadFileRequest: MessageFns<UploadFileRequest> = {
  encode(message: UploadFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadFileRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
    };
  },

  toJSON(message: UploadFileRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadFileRequest>, I>>(base?: I): UploadFileRequest {
    return UploadFileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadFileRequest>, I>>(object: I): UploadFileRequest {
    const message = createBaseUploadFileRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.project = object.project ?? "";
    return message;
  },
};

function createBaseUploadFileResponse(): UploadFileResponse {
  return { taskId: "", project: "", status: "" };
}

export const UploadFileResponse: MessageFns<UploadFileResponse> = {
  encode(message: UploadFileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadFileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadFileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadFileResponse {
    return {
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: UploadFileResponse): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadFileResponse>, I>>(base?: I): UploadFileResponse {
    return UploadFileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadFileResponse>, I>>(object: I): UploadFileResponse {
    const message = createBaseUploadFileResponse();
    message.taskId = object.taskId ?? "";
    message.project = object.project ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseSearchDocumentsRequest(): SearchDocumentsRequest {
  return { serverUrl: "", project: "", query: "", topK: 0 };
}

export const SearchDocumentsRequest: MessageFns<SearchDocumentsRequest> = {
  encode(message: SearchDocumentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    if (message.query !== "") {
      writer.uint32(26).string(message.query);
    }
    if (message.topK !== 0) {
      writer.uint32(32).int32(message.topK);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchDocumentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchDocumentsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.topK = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchDocumentsRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      topK: isSet(object.topK)
        ? globalThis.Number(object.topK)
        : isSet(object.top_k)
        ? globalThis.Number(object.top_k)
        : 0,
    };
  },

  toJSON(message: SearchDocumentsRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.topK !== 0) {
      obj.topK = Math.round(message.topK);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchDocumentsRequest>, I>>(base?: I): SearchDocumentsRequest {
    return SearchDocumentsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchDocumentsRequest>, I>>(object: I): SearchDocumentsRequest {
    const message = createBaseSearchDocumentsRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.project = object.project ?? "";
    message.query = object.query ?? "";
    message.topK = object.topK ?? 0;
    return message;
  },
};

function createBaseSearchResult(): SearchResult {
  return { score: 0, docId: "", sourceName: "", page: 0, chunkIndex: 0, text: "" };
}

export const SearchResult: MessageFns<SearchResult> = {
  encode(message: SearchResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.score !== 0) {
      writer.uint32(9).double(message.score);
    }
    if (message.docId !== "") {
      writer.uint32(18).string(message.docId);
    }
    if (message.sourceName !== "") {
      writer.uint32(26).string(message.sourceName);
    }
    if (message.page !== 0) {
      writer.uint32(32).int32(message.page);
    }
    if (message.chunkIndex !== 0) {
      writer.uint32(40).int32(message.chunkIndex);
    }
    if (message.text !== "") {
      writer.uint32(50).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.score = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.docId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sourceName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.chunkIndex = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchResult {
    return {
      score: isSet(object.score) ? globalThis.Number(object.score) : 0,
      docId: isSet(object.docId)
        ? globalThis.String(object.docId)
        : isSet(object.doc_id)
        ? globalThis.String(object.doc_id)
        : "",
      sourceName: isSet(object.sourceName)
        ? globalThis.String(object.sourceName)
        : isSet(object.source_name)
        ? globalThis.String(object.source_name)
        : "",
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      chunkIndex: isSet(object.chunkIndex)
        ? globalThis.Number(object.chunkIndex)
        : isSet(object.chunk_index)
        ? globalThis.Number(object.chunk_index)
        : 0,
      text: isSet(object.text) ? globalThis.String(object.text) : "",
    };
  },

  toJSON(message: SearchResult): unknown {
    const obj: any = {};
    if (message.score !== 0) {
      obj.score = message.score;
    }
    if (message.docId !== "") {
      obj.docId = message.docId;
    }
    if (message.sourceName !== "") {
      obj.sourceName = message.sourceName;
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.chunkIndex !== 0) {
      obj.chunkIndex = Math.round(message.chunkIndex);
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchResult>, I>>(base?: I): SearchResult {
    return SearchResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchResult>, I>>(object: I): SearchResult {
    const message = createBaseSearchResult();
    message.score = object.score ?? 0;
    message.docId = object.docId ?? "";
    message.sourceName = object.sourceName ?? "";
    message.page = object.page ?? 0;
    message.chunkIndex = object.chunkIndex ?? 0;
    message.text = object.text ?? "";
    return message;
  },
};

function createBaseSearchDocumentsResponse(): SearchDocumentsResponse {
  return { project: "", query: "", results: [] };
}

export const SearchDocumentsResponse: MessageFns<SearchDocumentsResponse> = {
  encode(message: SearchDocumentsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.project !== "") {
      writer.uint32(10).string(message.project);
    }
    if (message.query !== "") {
      writer.uint32(18).string(message.query);
    }
    for (const v of message.results) {
      SearchResult.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchDocumentsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchDocumentsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.results.push(SearchResult.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchDocumentsResponse {
    return {
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => SearchResult.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SearchDocumentsResponse): unknown {
    const obj: any = {};
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.results?.length) {
      obj.results = message.results.map((e) => SearchResult.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchDocumentsResponse>, I>>(base?: I): SearchDocumentsResponse {
    return SearchDocumentsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchDocumentsResponse>, I>>(object: I): SearchDocumentsResponse {
    const message = createBaseSearchDocumentsResponse();
    message.project = object.project ?? "";
    message.query = object.query ?? "";
    message.results = object.results?.map((e) => SearchResult.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDocsIndexTool(): DocsIndexTool {
  return { name: "", description: "" };
}

export const DocsIndexTool: MessageFns<DocsIndexTool> = {
  encode(message: DocsIndexTool, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocsIndexTool {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocsIndexTool();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocsIndexTool {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: DocsIndexTool): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocsIndexTool>, I>>(base?: I): DocsIndexTool {
    return DocsIndexTool.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocsIndexTool>, I>>(object: I): DocsIndexTool {
    const message = createBaseDocsIndexTool();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseDocsIndexTools(): DocsIndexTools {
  return { tools: [] };
}

export const DocsIndexTools: MessageFns<DocsIndexTools> = {
  encode(message: DocsIndexTools, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tools) {
      DocsIndexTool.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocsIndexTools {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocsIndexTools();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tools.push(DocsIndexTool.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocsIndexTools {
    return {
      tools: globalThis.Array.isArray(object?.tools) ? object.tools.map((e: any) => DocsIndexTool.fromJSON(e)) : [],
    };
  },

  toJSON(message: DocsIndexTools): unknown {
    const obj: any = {};
    if (message.tools?.length) {
      obj.tools = message.tools.map((e) => DocsIndexTool.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocsIndexTools>, I>>(base?: I): DocsIndexTools {
    return DocsIndexTools.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocsIndexTools>, I>>(object: I): DocsIndexTools {
    const message = createBaseDocsIndexTools();
    message.tools = object.tools?.map((e) => DocsIndexTool.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRegisterMcpRequest(): RegisterMcpRequest {
  return { serverUrl: "" };
}

export const RegisterMcpRequest: MessageFns<RegisterMcpRequest> = {
  encode(message: RegisterMcpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterMcpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterMcpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterMcpRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
    };
  },

  toJSON(message: RegisterMcpRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterMcpRequest>, I>>(base?: I): RegisterMcpRequest {
    return RegisterMcpRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterMcpRequest>, I>>(object: I): RegisterMcpRequest {
    const message = createBaseRegisterMcpRequest();
    message.serverUrl = object.serverUrl ?? "";
    return message;
  },
};

function createBaseUnregisterMcpRequest(): UnregisterMcpRequest {
  return {};
}

export const UnregisterMcpRequest: MessageFns<UnregisterMcpRequest> = {
  encode(_: UnregisterMcpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnregisterMcpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnregisterMcpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): UnregisterMcpRequest {
    return {};
  },

  toJSON(_: UnregisterMcpRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<UnregisterMcpRequest>, I>>(base?: I): UnregisterMcpRequest {
    return UnregisterMcpRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnregisterMcpRequest>, I>>(_: I): UnregisterMcpRequest {
    const message = createBaseUnregisterMcpRequest();
    return message;
  },
};

function createBaseCreateProjectRequest(): CreateProjectRequest {
  return { serverUrl: "", name: "" };
}

export const CreateProjectRequest: MessageFns<CreateProjectRequest> = {
  encode(message: CreateProjectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateProjectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProjectRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: CreateProjectRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateProjectRequest>, I>>(base?: I): CreateProjectRequest {
    return CreateProjectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateProjectRequest>, I>>(object: I): CreateProjectRequest {
    const message = createBaseCreateProjectRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseCreateProjectResponse(): CreateProjectResponse {
  return { project: "", status: "" };
}

export const CreateProjectResponse: MessageFns<CreateProjectResponse> = {
  encode(message: CreateProjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.project !== "") {
      writer.uint32(10).string(message.project);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateProjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProjectResponse {
    return {
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: CreateProjectResponse): unknown {
    const obj: any = {};
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateProjectResponse>, I>>(base?: I): CreateProjectResponse {
    return CreateProjectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateProjectResponse>, I>>(object: I): CreateProjectResponse {
    const message = createBaseCreateProjectResponse();
    message.project = object.project ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseDeleteDocumentRequest(): DeleteDocumentRequest {
  return { serverUrl: "", project: "", source: "" };
}

export const DeleteDocumentRequest: MessageFns<DeleteDocumentRequest> = {
  encode(message: DeleteDocumentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    if (message.source !== "") {
      writer.uint32(26).string(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteDocumentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteDocumentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.source = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteDocumentRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      source: isSet(object.source) ? globalThis.String(object.source) : "",
    };
  },

  toJSON(message: DeleteDocumentRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.source !== "") {
      obj.source = message.source;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteDocumentRequest>, I>>(base?: I): DeleteDocumentRequest {
    return DeleteDocumentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteDocumentRequest>, I>>(object: I): DeleteDocumentRequest {
    const message = createBaseDeleteDocumentRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.project = object.project ?? "";
    message.source = object.source ?? "";
    return message;
  },
};

function createBaseDeleteDocumentResponse(): DeleteDocumentResponse {
  return { status: "" };
}

export const DeleteDocumentResponse: MessageFns<DeleteDocumentResponse> = {
  encode(message: DeleteDocumentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteDocumentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteDocumentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteDocumentResponse {
    return { status: isSet(object.status) ? globalThis.String(object.status) : "" };
  },

  toJSON(message: DeleteDocumentResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteDocumentResponse>, I>>(base?: I): DeleteDocumentResponse {
    return DeleteDocumentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteDocumentResponse>, I>>(object: I): DeleteDocumentResponse {
    const message = createBaseDeleteDocumentResponse();
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseTaskStatusRequest(): TaskStatusRequest {
  return { serverUrl: "", taskId: "" };
}

export const TaskStatusRequest: MessageFns<TaskStatusRequest> = {
  encode(message: TaskStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.taskId !== "") {
      writer.uint32(18).string(message.taskId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskStatusRequest {
    return {
      serverUrl: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : "",
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
    };
  },

  toJSON(message: TaskStatusRequest): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskStatusRequest>, I>>(base?: I): TaskStatusRequest {
    return TaskStatusRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskStatusRequest>, I>>(object: I): TaskStatusRequest {
    const message = createBaseTaskStatusRequest();
    message.serverUrl = object.serverUrl ?? "";
    message.taskId = object.taskId ?? "";
    return message;
  },
};

function createBaseTaskStatusResponse(): TaskStatusResponse {
  return { id: "", project: "", status: "", progress: 0, message: "", detail: "" };
}

export const TaskStatusResponse: MessageFns<TaskStatusResponse> = {
  encode(message: TaskStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.project !== "") {
      writer.uint32(18).string(message.project);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    if (message.progress !== 0) {
      writer.uint32(37).float(message.progress);
    }
    if (message.message !== "") {
      writer.uint32(42).string(message.message);
    }
    if (message.detail !== "") {
      writer.uint32(50).string(message.detail);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.project = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.progress = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.detail = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskStatusResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      project: isSet(object.project) ? globalThis.String(object.project) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      progress: isSet(object.progress) ? globalThis.Number(object.progress) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      detail: isSet(object.detail) ? globalThis.String(object.detail) : "",
    };
  },

  toJSON(message: TaskStatusResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.project !== "") {
      obj.project = message.project;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.progress !== 0) {
      obj.progress = message.progress;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.detail !== "") {
      obj.detail = message.detail;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskStatusResponse>, I>>(base?: I): TaskStatusResponse {
    return TaskStatusResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskStatusResponse>, I>>(object: I): TaskStatusResponse {
    const message = createBaseTaskStatusResponse();
    message.id = object.id ?? "";
    message.project = object.project ?? "";
    message.status = object.status ?? "";
    message.progress = object.progress ?? 0;
    message.message = object.message ?? "";
    message.detail = object.detail ?? "";
    return message;
  },
};

export type DocsIndexServiceDefinition = typeof DocsIndexServiceDefinition;
export const DocsIndexServiceDefinition = {
  name: "DocsIndexService",
  fullName: "cline.DocsIndexService",
  methods: {
    ping: {
      name: "ping",
      requestType: PingRequest as typeof PingRequest,
      requestStream: false,
      responseType: PingResponse as typeof PingResponse,
      responseStream: false,
      options: {},
    },
    listProjects: {
      name: "listProjects",
      requestType: ListProjectsRequest as typeof ListProjectsRequest,
      requestStream: false,
      responseType: ListProjectsResponse as typeof ListProjectsResponse,
      responseStream: false,
      options: {},
    },
    createProject: {
      name: "createProject",
      requestType: CreateProjectRequest as typeof CreateProjectRequest,
      requestStream: false,
      responseType: CreateProjectResponse as typeof CreateProjectResponse,
      responseStream: false,
      options: {},
    },
    uploadFile: {
      name: "uploadFile",
      requestType: UploadFileRequest as typeof UploadFileRequest,
      requestStream: false,
      responseType: UploadFileResponse as typeof UploadFileResponse,
      responseStream: false,
      options: {},
    },
    indexUrl: {
      name: "indexUrl",
      requestType: IndexUrlRequest as typeof IndexUrlRequest,
      requestStream: false,
      responseType: IndexUrlResponse as typeof IndexUrlResponse,
      responseStream: false,
      options: {},
    },
    getTask: {
      name: "getTask",
      requestType: TaskStatusRequest as typeof TaskStatusRequest,
      requestStream: false,
      responseType: TaskStatusResponse as typeof TaskStatusResponse,
      responseStream: false,
      options: {},
    },
    searchDocuments: {
      name: "searchDocuments",
      requestType: SearchDocumentsRequest as typeof SearchDocumentsRequest,
      requestStream: false,
      responseType: SearchDocumentsResponse as typeof SearchDocumentsResponse,
      responseStream: false,
      options: {},
    },
    deleteDocument: {
      name: "deleteDocument",
      requestType: DeleteDocumentRequest as typeof DeleteDocumentRequest,
      requestStream: false,
      responseType: DeleteDocumentResponse as typeof DeleteDocumentResponse,
      responseStream: false,
      options: {},
    },
    listDocsIndexTools: {
      name: "listDocsIndexTools",
      requestType: EmptyRequest as typeof EmptyRequest,
      requestStream: false,
      responseType: DocsIndexTools as typeof DocsIndexTools,
      responseStream: false,
      options: {},
    },
    registerMcpServer: {
      name: "registerMcpServer",
      requestType: RegisterMcpRequest as typeof RegisterMcpRequest,
      requestStream: false,
      responseType: Empty as typeof Empty,
      responseStream: false,
      options: {},
    },
    unregisterMcpServer: {
      name: "unregisterMcpServer",
      requestType: UnregisterMcpRequest as typeof UnregisterMcpRequest,
      requestStream: false,
      responseType: Empty as typeof Empty,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
