// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: cline/marketplace.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { EmptyRequest } from "./common";

export interface MarketplaceTag {
  label: string;
  color?: string | undefined;
}

export interface MarketplaceCounts {
  tools?: number | undefined;
  prompts?: number | undefined;
  resources?: number | undefined;
}

export interface MarketplaceEnvVar {
  name: string;
  required: boolean;
  description?: string | undefined;
  url?: string | undefined;
}

export interface MarketplaceInstall {
  args: string[];
  env: MarketplaceEnvVar[];
  command?: string | undefined;
  notes?: string | undefined;
}

export interface MarketplaceEntry {
  id: string;
  type: string;
  name: string;
  tagline?: string | undefined;
  description?: string | undefined;
  tags: string[];
  tagObjects: MarketplaceTag[];
  author?: string | undefined;
  sourceUrl?: string | undefined;
  homepageUrl?: string | undefined;
  counts?: MarketplaceCounts | undefined;
  install?: MarketplaceInstall | undefined;
}

export interface MarketplaceCatalog {
  entries: MarketplaceEntry[];
}

export interface MarketplaceEntriesRequest {
  entries: MarketplaceEntry[];
}

export interface MarketplaceInstalledEntries {
  installedKeys: string[];
}

export interface MarketplaceLocalInstalledEntry {
  id: string;
  type: string;
  name: string;
  description?: string | undefined;
  path?: string | undefined;
  source?: string | undefined;
  enabled: boolean;
}

export interface MarketplaceLocalInstalledEntries {
  entries: MarketplaceLocalInstalledEntry[];
}

export interface ToggleMarketplaceLocalInstalledEntryRequest {
  entry: MarketplaceLocalInstalledEntry | undefined;
  enabled: boolean;
}

export interface MarketplaceLocalInstalledEntryRequest {
  entry: MarketplaceLocalInstalledEntry | undefined;
}

export interface MarketplaceEntryRequest {
  entry: MarketplaceEntry | undefined;
}

export interface MarketplaceInstallResult {
  id: string;
  type: string;
  status: string;
  message: string;
  output?: string | undefined;
}

function createBaseMarketplaceTag(): MarketplaceTag {
  return { label: "", color: undefined };
}

export const MarketplaceTag: MessageFns<MarketplaceTag> = {
  encode(message: MarketplaceTag, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.label !== "") {
      writer.uint32(10).string(message.label);
    }
    if (message.color !== undefined) {
      writer.uint32(18).string(message.color);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceTag {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceTag();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.label = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.color = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceTag {
    return {
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      color: isSet(object.color) ? globalThis.String(object.color) : undefined,
    };
  },

  toJSON(message: MarketplaceTag): unknown {
    const obj: any = {};
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.color !== undefined) {
      obj.color = message.color;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceTag>, I>>(base?: I): MarketplaceTag {
    return MarketplaceTag.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceTag>, I>>(object: I): MarketplaceTag {
    const message = createBaseMarketplaceTag();
    message.label = object.label ?? "";
    message.color = object.color ?? undefined;
    return message;
  },
};

function createBaseMarketplaceCounts(): MarketplaceCounts {
  return { tools: undefined, prompts: undefined, resources: undefined };
}

export const MarketplaceCounts: MessageFns<MarketplaceCounts> = {
  encode(message: MarketplaceCounts, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tools !== undefined) {
      writer.uint32(8).int32(message.tools);
    }
    if (message.prompts !== undefined) {
      writer.uint32(16).int32(message.prompts);
    }
    if (message.resources !== undefined) {
      writer.uint32(24).int32(message.resources);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceCounts {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceCounts();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tools = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.prompts = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.resources = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceCounts {
    return {
      tools: isSet(object.tools) ? globalThis.Number(object.tools) : undefined,
      prompts: isSet(object.prompts) ? globalThis.Number(object.prompts) : undefined,
      resources: isSet(object.resources) ? globalThis.Number(object.resources) : undefined,
    };
  },

  toJSON(message: MarketplaceCounts): unknown {
    const obj: any = {};
    if (message.tools !== undefined) {
      obj.tools = Math.round(message.tools);
    }
    if (message.prompts !== undefined) {
      obj.prompts = Math.round(message.prompts);
    }
    if (message.resources !== undefined) {
      obj.resources = Math.round(message.resources);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceCounts>, I>>(base?: I): MarketplaceCounts {
    return MarketplaceCounts.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceCounts>, I>>(object: I): MarketplaceCounts {
    const message = createBaseMarketplaceCounts();
    message.tools = object.tools ?? undefined;
    message.prompts = object.prompts ?? undefined;
    message.resources = object.resources ?? undefined;
    return message;
  },
};

function createBaseMarketplaceEnvVar(): MarketplaceEnvVar {
  return { name: "", required: false, description: undefined, url: undefined };
}

export const MarketplaceEnvVar: MessageFns<MarketplaceEnvVar> = {
  encode(message: MarketplaceEnvVar, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.required !== false) {
      writer.uint32(16).bool(message.required);
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    if (message.url !== undefined) {
      writer.uint32(34).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceEnvVar {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceEnvVar();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.required = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceEnvVar {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      required: isSet(object.required) ? globalThis.Boolean(object.required) : false,
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      url: isSet(object.url) ? globalThis.String(object.url) : undefined,
    };
  },

  toJSON(message: MarketplaceEnvVar): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.required !== false) {
      obj.required = message.required;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.url !== undefined) {
      obj.url = message.url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceEnvVar>, I>>(base?: I): MarketplaceEnvVar {
    return MarketplaceEnvVar.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceEnvVar>, I>>(object: I): MarketplaceEnvVar {
    const message = createBaseMarketplaceEnvVar();
    message.name = object.name ?? "";
    message.required = object.required ?? false;
    message.description = object.description ?? undefined;
    message.url = object.url ?? undefined;
    return message;
  },
};

function createBaseMarketplaceInstall(): MarketplaceInstall {
  return { args: [], env: [], command: undefined, notes: undefined };
}

export const MarketplaceInstall: MessageFns<MarketplaceInstall> = {
  encode(message: MarketplaceInstall, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.args) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.env) {
      MarketplaceEnvVar.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.command !== undefined) {
      writer.uint32(26).string(message.command);
    }
    if (message.notes !== undefined) {
      writer.uint32(34).string(message.notes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceInstall {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceInstall();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.args.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.env.push(MarketplaceEnvVar.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.command = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceInstall {
    return {
      args: globalThis.Array.isArray(object?.args) ? object.args.map((e: any) => globalThis.String(e)) : [],
      env: globalThis.Array.isArray(object?.env) ? object.env.map((e: any) => MarketplaceEnvVar.fromJSON(e)) : [],
      command: isSet(object.command) ? globalThis.String(object.command) : undefined,
      notes: isSet(object.notes) ? globalThis.String(object.notes) : undefined,
    };
  },

  toJSON(message: MarketplaceInstall): unknown {
    const obj: any = {};
    if (message.args?.length) {
      obj.args = message.args;
    }
    if (message.env?.length) {
      obj.env = message.env.map((e) => MarketplaceEnvVar.toJSON(e));
    }
    if (message.command !== undefined) {
      obj.command = message.command;
    }
    if (message.notes !== undefined) {
      obj.notes = message.notes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceInstall>, I>>(base?: I): MarketplaceInstall {
    return MarketplaceInstall.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceInstall>, I>>(object: I): MarketplaceInstall {
    const message = createBaseMarketplaceInstall();
    message.args = object.args?.map((e) => e) || [];
    message.env = object.env?.map((e) => MarketplaceEnvVar.fromPartial(e)) || [];
    message.command = object.command ?? undefined;
    message.notes = object.notes ?? undefined;
    return message;
  },
};

function createBaseMarketplaceEntry(): MarketplaceEntry {
  return {
    id: "",
    type: "",
    name: "",
    tagline: undefined,
    description: undefined,
    tags: [],
    tagObjects: [],
    author: undefined,
    sourceUrl: undefined,
    homepageUrl: undefined,
    counts: undefined,
    install: undefined,
  };
}

export const MarketplaceEntry: MessageFns<MarketplaceEntry> = {
  encode(message: MarketplaceEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.tagline !== undefined) {
      writer.uint32(34).string(message.tagline);
    }
    if (message.description !== undefined) {
      writer.uint32(42).string(message.description);
    }
    for (const v of message.tags) {
      writer.uint32(50).string(v!);
    }
    for (const v of message.tagObjects) {
      MarketplaceTag.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.author !== undefined) {
      writer.uint32(66).string(message.author);
    }
    if (message.sourceUrl !== undefined) {
      writer.uint32(74).string(message.sourceUrl);
    }
    if (message.homepageUrl !== undefined) {
      writer.uint32(82).string(message.homepageUrl);
    }
    if (message.counts !== undefined) {
      MarketplaceCounts.encode(message.counts, writer.uint32(90).fork()).join();
    }
    if (message.install !== undefined) {
      MarketplaceInstall.encode(message.install, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tagline = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.tagObjects.push(MarketplaceTag.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.sourceUrl = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.homepageUrl = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.counts = MarketplaceCounts.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.install = MarketplaceInstall.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceEntry {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      tagline: isSet(object.tagline) ? globalThis.String(object.tagline) : undefined,
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      tagObjects: globalThis.Array.isArray(object?.tagObjects)
        ? object.tagObjects.map((e: any) => MarketplaceTag.fromJSON(e))
        : globalThis.Array.isArray(object?.tag_objects)
        ? object.tag_objects.map((e: any) => MarketplaceTag.fromJSON(e))
        : [],
      author: isSet(object.author) ? globalThis.String(object.author) : undefined,
      sourceUrl: isSet(object.sourceUrl)
        ? globalThis.String(object.sourceUrl)
        : isSet(object.source_url)
        ? globalThis.String(object.source_url)
        : undefined,
      homepageUrl: isSet(object.homepageUrl)
        ? globalThis.String(object.homepageUrl)
        : isSet(object.homepage_url)
        ? globalThis.String(object.homepage_url)
        : undefined,
      counts: isSet(object.counts) ? MarketplaceCounts.fromJSON(object.counts) : undefined,
      install: isSet(object.install) ? MarketplaceInstall.fromJSON(object.install) : undefined,
    };
  },

  toJSON(message: MarketplaceEntry): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.tagline !== undefined) {
      obj.tagline = message.tagline;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.tagObjects?.length) {
      obj.tagObjects = message.tagObjects.map((e) => MarketplaceTag.toJSON(e));
    }
    if (message.author !== undefined) {
      obj.author = message.author;
    }
    if (message.sourceUrl !== undefined) {
      obj.sourceUrl = message.sourceUrl;
    }
    if (message.homepageUrl !== undefined) {
      obj.homepageUrl = message.homepageUrl;
    }
    if (message.counts !== undefined) {
      obj.counts = MarketplaceCounts.toJSON(message.counts);
    }
    if (message.install !== undefined) {
      obj.install = MarketplaceInstall.toJSON(message.install);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceEntry>, I>>(base?: I): MarketplaceEntry {
    return MarketplaceEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceEntry>, I>>(object: I): MarketplaceEntry {
    const message = createBaseMarketplaceEntry();
    message.id = object.id ?? "";
    message.type = object.type ?? "";
    message.name = object.name ?? "";
    message.tagline = object.tagline ?? undefined;
    message.description = object.description ?? undefined;
    message.tags = object.tags?.map((e) => e) || [];
    message.tagObjects = object.tagObjects?.map((e) => MarketplaceTag.fromPartial(e)) || [];
    message.author = object.author ?? undefined;
    message.sourceUrl = object.sourceUrl ?? undefined;
    message.homepageUrl = object.homepageUrl ?? undefined;
    message.counts = (object.counts !== undefined && object.counts !== null)
      ? MarketplaceCounts.fromPartial(object.counts)
      : undefined;
    message.install = (object.install !== undefined && object.install !== null)
      ? MarketplaceInstall.fromPartial(object.install)
      : undefined;
    return message;
  },
};

function createBaseMarketplaceCatalog(): MarketplaceCatalog {
  return { entries: [] };
}

export const MarketplaceCatalog: MessageFns<MarketplaceCatalog> = {
  encode(message: MarketplaceCatalog, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entries) {
      MarketplaceEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceCatalog {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceCatalog();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entries.push(MarketplaceEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceCatalog {
    return {
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => MarketplaceEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MarketplaceCatalog): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => MarketplaceEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceCatalog>, I>>(base?: I): MarketplaceCatalog {
    return MarketplaceCatalog.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceCatalog>, I>>(object: I): MarketplaceCatalog {
    const message = createBaseMarketplaceCatalog();
    message.entries = object.entries?.map((e) => MarketplaceEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMarketplaceEntriesRequest(): MarketplaceEntriesRequest {
  return { entries: [] };
}

export const MarketplaceEntriesRequest: MessageFns<MarketplaceEntriesRequest> = {
  encode(message: MarketplaceEntriesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entries) {
      MarketplaceEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceEntriesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceEntriesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entries.push(MarketplaceEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceEntriesRequest {
    return {
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => MarketplaceEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MarketplaceEntriesRequest): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => MarketplaceEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceEntriesRequest>, I>>(base?: I): MarketplaceEntriesRequest {
    return MarketplaceEntriesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceEntriesRequest>, I>>(object: I): MarketplaceEntriesRequest {
    const message = createBaseMarketplaceEntriesRequest();
    message.entries = object.entries?.map((e) => MarketplaceEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMarketplaceInstalledEntries(): MarketplaceInstalledEntries {
  return { installedKeys: [] };
}

export const MarketplaceInstalledEntries: MessageFns<MarketplaceInstalledEntries> = {
  encode(message: MarketplaceInstalledEntries, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.installedKeys) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceInstalledEntries {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceInstalledEntries();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.installedKeys.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceInstalledEntries {
    return {
      installedKeys: globalThis.Array.isArray(object?.installedKeys)
        ? object.installedKeys.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.installed_keys)
        ? object.installed_keys.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: MarketplaceInstalledEntries): unknown {
    const obj: any = {};
    if (message.installedKeys?.length) {
      obj.installedKeys = message.installedKeys;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceInstalledEntries>, I>>(base?: I): MarketplaceInstalledEntries {
    return MarketplaceInstalledEntries.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceInstalledEntries>, I>>(object: I): MarketplaceInstalledEntries {
    const message = createBaseMarketplaceInstalledEntries();
    message.installedKeys = object.installedKeys?.map((e) => e) || [];
    return message;
  },
};

function createBaseMarketplaceLocalInstalledEntry(): MarketplaceLocalInstalledEntry {
  return { id: "", type: "", name: "", description: undefined, path: undefined, source: undefined, enabled: false };
}

export const MarketplaceLocalInstalledEntry: MessageFns<MarketplaceLocalInstalledEntry> = {
  encode(message: MarketplaceLocalInstalledEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(34).string(message.description);
    }
    if (message.path !== undefined) {
      writer.uint32(42).string(message.path);
    }
    if (message.source !== undefined) {
      writer.uint32(50).string(message.source);
    }
    if (message.enabled !== false) {
      writer.uint32(56).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceLocalInstalledEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceLocalInstalledEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceLocalInstalledEntry {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      path: isSet(object.path) ? globalThis.String(object.path) : undefined,
      source: isSet(object.source) ? globalThis.String(object.source) : undefined,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
    };
  },

  toJSON(message: MarketplaceLocalInstalledEntry): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.path !== undefined) {
      obj.path = message.path;
    }
    if (message.source !== undefined) {
      obj.source = message.source;
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceLocalInstalledEntry>, I>>(base?: I): MarketplaceLocalInstalledEntry {
    return MarketplaceLocalInstalledEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceLocalInstalledEntry>, I>>(
    object: I,
  ): MarketplaceLocalInstalledEntry {
    const message = createBaseMarketplaceLocalInstalledEntry();
    message.id = object.id ?? "";
    message.type = object.type ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.path = object.path ?? undefined;
    message.source = object.source ?? undefined;
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseMarketplaceLocalInstalledEntries(): MarketplaceLocalInstalledEntries {
  return { entries: [] };
}

export const MarketplaceLocalInstalledEntries: MessageFns<MarketplaceLocalInstalledEntries> = {
  encode(message: MarketplaceLocalInstalledEntries, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entries) {
      MarketplaceLocalInstalledEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceLocalInstalledEntries {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceLocalInstalledEntries();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entries.push(MarketplaceLocalInstalledEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceLocalInstalledEntries {
    return {
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => MarketplaceLocalInstalledEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MarketplaceLocalInstalledEntries): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => MarketplaceLocalInstalledEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceLocalInstalledEntries>, I>>(
    base?: I,
  ): MarketplaceLocalInstalledEntries {
    return MarketplaceLocalInstalledEntries.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceLocalInstalledEntries>, I>>(
    object: I,
  ): MarketplaceLocalInstalledEntries {
    const message = createBaseMarketplaceLocalInstalledEntries();
    message.entries = object.entries?.map((e) => MarketplaceLocalInstalledEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseToggleMarketplaceLocalInstalledEntryRequest(): ToggleMarketplaceLocalInstalledEntryRequest {
  return { entry: undefined, enabled: false };
}

export const ToggleMarketplaceLocalInstalledEntryRequest: MessageFns<ToggleMarketplaceLocalInstalledEntryRequest> = {
  encode(
    message: ToggleMarketplaceLocalInstalledEntryRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.entry !== undefined) {
      MarketplaceLocalInstalledEntry.encode(message.entry, writer.uint32(10).fork()).join();
    }
    if (message.enabled !== false) {
      writer.uint32(16).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToggleMarketplaceLocalInstalledEntryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToggleMarketplaceLocalInstalledEntryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entry = MarketplaceLocalInstalledEntry.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToggleMarketplaceLocalInstalledEntryRequest {
    return {
      entry: isSet(object.entry) ? MarketplaceLocalInstalledEntry.fromJSON(object.entry) : undefined,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
    };
  },

  toJSON(message: ToggleMarketplaceLocalInstalledEntryRequest): unknown {
    const obj: any = {};
    if (message.entry !== undefined) {
      obj.entry = MarketplaceLocalInstalledEntry.toJSON(message.entry);
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToggleMarketplaceLocalInstalledEntryRequest>, I>>(
    base?: I,
  ): ToggleMarketplaceLocalInstalledEntryRequest {
    return ToggleMarketplaceLocalInstalledEntryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToggleMarketplaceLocalInstalledEntryRequest>, I>>(
    object: I,
  ): ToggleMarketplaceLocalInstalledEntryRequest {
    const message = createBaseToggleMarketplaceLocalInstalledEntryRequest();
    message.entry = (object.entry !== undefined && object.entry !== null)
      ? MarketplaceLocalInstalledEntry.fromPartial(object.entry)
      : undefined;
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseMarketplaceLocalInstalledEntryRequest(): MarketplaceLocalInstalledEntryRequest {
  return { entry: undefined };
}

export const MarketplaceLocalInstalledEntryRequest: MessageFns<MarketplaceLocalInstalledEntryRequest> = {
  encode(message: MarketplaceLocalInstalledEntryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entry !== undefined) {
      MarketplaceLocalInstalledEntry.encode(message.entry, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceLocalInstalledEntryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceLocalInstalledEntryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entry = MarketplaceLocalInstalledEntry.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceLocalInstalledEntryRequest {
    return { entry: isSet(object.entry) ? MarketplaceLocalInstalledEntry.fromJSON(object.entry) : undefined };
  },

  toJSON(message: MarketplaceLocalInstalledEntryRequest): unknown {
    const obj: any = {};
    if (message.entry !== undefined) {
      obj.entry = MarketplaceLocalInstalledEntry.toJSON(message.entry);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceLocalInstalledEntryRequest>, I>>(
    base?: I,
  ): MarketplaceLocalInstalledEntryRequest {
    return MarketplaceLocalInstalledEntryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceLocalInstalledEntryRequest>, I>>(
    object: I,
  ): MarketplaceLocalInstalledEntryRequest {
    const message = createBaseMarketplaceLocalInstalledEntryRequest();
    message.entry = (object.entry !== undefined && object.entry !== null)
      ? MarketplaceLocalInstalledEntry.fromPartial(object.entry)
      : undefined;
    return message;
  },
};

function createBaseMarketplaceEntryRequest(): MarketplaceEntryRequest {
  return { entry: undefined };
}

export const MarketplaceEntryRequest: MessageFns<MarketplaceEntryRequest> = {
  encode(message: MarketplaceEntryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entry !== undefined) {
      MarketplaceEntry.encode(message.entry, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceEntryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceEntryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entry = MarketplaceEntry.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceEntryRequest {
    return { entry: isSet(object.entry) ? MarketplaceEntry.fromJSON(object.entry) : undefined };
  },

  toJSON(message: MarketplaceEntryRequest): unknown {
    const obj: any = {};
    if (message.entry !== undefined) {
      obj.entry = MarketplaceEntry.toJSON(message.entry);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceEntryRequest>, I>>(base?: I): MarketplaceEntryRequest {
    return MarketplaceEntryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceEntryRequest>, I>>(object: I): MarketplaceEntryRequest {
    const message = createBaseMarketplaceEntryRequest();
    message.entry = (object.entry !== undefined && object.entry !== null)
      ? MarketplaceEntry.fromPartial(object.entry)
      : undefined;
    return message;
  },
};

function createBaseMarketplaceInstallResult(): MarketplaceInstallResult {
  return { id: "", type: "", status: "", message: "", output: undefined };
}

export const MarketplaceInstallResult: MessageFns<MarketplaceInstallResult> = {
  encode(message: MarketplaceInstallResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    if (message.message !== "") {
      writer.uint32(34).string(message.message);
    }
    if (message.output !== undefined) {
      writer.uint32(42).string(message.output);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketplaceInstallResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketplaceInstallResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.output = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketplaceInstallResult {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      output: isSet(object.output) ? globalThis.String(object.output) : undefined,
    };
  },

  toJSON(message: MarketplaceInstallResult): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.output !== undefined) {
      obj.output = message.output;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketplaceInstallResult>, I>>(base?: I): MarketplaceInstallResult {
    return MarketplaceInstallResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketplaceInstallResult>, I>>(object: I): MarketplaceInstallResult {
    const message = createBaseMarketplaceInstallResult();
    message.id = object.id ?? "";
    message.type = object.type ?? "";
    message.status = object.status ?? "";
    message.message = object.message ?? "";
    message.output = object.output ?? undefined;
    return message;
  },
};

export type MarketplaceServiceDefinition = typeof MarketplaceServiceDefinition;
export const MarketplaceServiceDefinition = {
  name: "MarketplaceService",
  fullName: "cline.MarketplaceService",
  methods: {
    getMarketplaceCatalog: {
      name: "getMarketplaceCatalog",
      requestType: EmptyRequest as typeof EmptyRequest,
      requestStream: false,
      responseType: MarketplaceCatalog as typeof MarketplaceCatalog,
      responseStream: false,
      options: {},
    },
    listMarketplaceLocalInstalledEntries: {
      name: "listMarketplaceLocalInstalledEntries",
      requestType: EmptyRequest as typeof EmptyRequest,
      requestStream: false,
      responseType: MarketplaceLocalInstalledEntries as typeof MarketplaceLocalInstalledEntries,
      responseStream: false,
      options: {},
    },
    listMarketplaceInstalledEntries: {
      name: "listMarketplaceInstalledEntries",
      requestType: MarketplaceEntriesRequest as typeof MarketplaceEntriesRequest,
      requestStream: false,
      responseType: MarketplaceInstalledEntries as typeof MarketplaceInstalledEntries,
      responseStream: false,
      options: {},
    },
    installMarketplaceEntry: {
      name: "installMarketplaceEntry",
      requestType: MarketplaceEntryRequest as typeof MarketplaceEntryRequest,
      requestStream: false,
      responseType: MarketplaceInstallResult as typeof MarketplaceInstallResult,
      responseStream: false,
      options: {},
    },
    uninstallMarketplaceEntry: {
      name: "uninstallMarketplaceEntry",
      requestType: MarketplaceEntryRequest as typeof MarketplaceEntryRequest,
      requestStream: false,
      responseType: MarketplaceInstallResult as typeof MarketplaceInstallResult,
      responseStream: false,
      options: {},
    },
    toggleMarketplaceLocalInstalledEntry: {
      name: "toggleMarketplaceLocalInstalledEntry",
      requestType: ToggleMarketplaceLocalInstalledEntryRequest as typeof ToggleMarketplaceLocalInstalledEntryRequest,
      requestStream: false,
      responseType: MarketplaceLocalInstalledEntries as typeof MarketplaceLocalInstalledEntries,
      responseStream: false,
      options: {},
    },
    uninstallMarketplaceLocalInstalledEntry: {
      name: "uninstallMarketplaceLocalInstalledEntry",
      requestType: MarketplaceLocalInstalledEntryRequest as typeof MarketplaceLocalInstalledEntryRequest,
      requestStream: false,
      responseType: MarketplaceInstallResult as typeof MarketplaceInstallResult,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
