// GENERATED CODE -- DO NOT EDIT!
// Generated by scripts/generate-protobus-setup.mjs
import * as proto from "@shared/proto/index"
import { Callbacks, ProtoBusClient, StreamingOptions } from "./grpc-client-base"

export class AccountServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.AccountService"
	static async accountLoginClicked(request: proto.cline.EmptyRequest): Promise<proto.cline.String> {
		return AccountServiceClient.makeUnaryRequest(
			"accountLoginClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.String.fromJSON,
		)
	}
	static async accountLogoutClicked(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"accountLogoutClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static subscribeToAuthStatusUpdate(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.AuthState>,
		options?: StreamingOptions,
	): () => void {
		return AccountServiceClient.makeStreamingRequest(
			"subscribeToAuthStatusUpdate",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.AuthState.fromJSON,
			callbacks,
			options,
		)
	}
	static async authStateChanged(request: proto.cline.AuthStateChangedRequest): Promise<proto.cline.AuthState> {
		return AccountServiceClient.makeUnaryRequest(
			"authStateChanged",
			request,
			proto.cline.AuthStateChangedRequest.toJSON,
			proto.cline.AuthState.fromJSON,
		)
	}
	static async getUserCredits(request: proto.cline.EmptyRequest): Promise<proto.cline.UserCreditsData> {
		return AccountServiceClient.makeUnaryRequest(
			"getUserCredits",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.UserCreditsData.fromJSON,
		)
	}
	static async getOrganizationCredits(
		request: proto.cline.GetOrganizationCreditsRequest,
	): Promise<proto.cline.OrganizationCreditsData> {
		return AccountServiceClient.makeUnaryRequest(
			"getOrganizationCredits",
			request,
			proto.cline.GetOrganizationCreditsRequest.toJSON,
			proto.cline.OrganizationCreditsData.fromJSON,
		)
	}
	static async getUserOrganizations(request: proto.cline.EmptyRequest): Promise<proto.cline.UserOrganizationsResponse> {
		return AccountServiceClient.makeUnaryRequest(
			"getUserOrganizations",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.UserOrganizationsResponse.fromJSON,
		)
	}
	static async setUserOrganization(request: proto.cline.UserOrganizationUpdateRequest): Promise<proto.cline.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"setUserOrganization",
			request,
			proto.cline.UserOrganizationUpdateRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async openrouterAuthClicked(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"openrouterAuthClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async requestyAuthClicked(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"requestyAuthClicked",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async hicapAuthClicked(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"hicapAuthClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async getRedirectUrl(request: proto.cline.EmptyRequest): Promise<proto.cline.String> {
		return AccountServiceClient.makeUnaryRequest(
			"getRedirectUrl",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.String.fromJSON,
		)
	}
	static async openAiCodexSignIn(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"openAiCodexSignIn",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async openAiCodexSignOut(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return AccountServiceClient.makeUnaryRequest(
			"openAiCodexSignOut",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async submitLimitIncreaseRequest(request: proto.cline.EmptyRequest): Promise<proto.cline.SubmitLimitIncreaseResponse> {
		return AccountServiceClient.makeUnaryRequest(
			"submitLimitIncreaseRequest",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.SubmitLimitIncreaseResponse.fromJSON,
		)
	}
}
export class BrowserServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.BrowserService"
	static async getBrowserConnectionInfo(request: proto.cline.EmptyRequest): Promise<proto.cline.BrowserConnectionInfo> {
		return BrowserServiceClient.makeUnaryRequest(
			"getBrowserConnectionInfo",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.BrowserConnectionInfo.fromJSON,
		)
	}
	static async testBrowserConnection(request: proto.cline.StringRequest): Promise<proto.cline.BrowserConnection> {
		return BrowserServiceClient.makeUnaryRequest(
			"testBrowserConnection",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.BrowserConnection.fromJSON,
		)
	}
	static async discoverBrowser(request: proto.cline.EmptyRequest): Promise<proto.cline.BrowserConnection> {
		return BrowserServiceClient.makeUnaryRequest(
			"discoverBrowser",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.BrowserConnection.fromJSON,
		)
	}
	static async getDetectedChromePath(request: proto.cline.EmptyRequest): Promise<proto.cline.ChromePath> {
		return BrowserServiceClient.makeUnaryRequest(
			"getDetectedChromePath",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.ChromePath.fromJSON,
		)
	}
	static async relaunchChromeDebugMode(request: proto.cline.EmptyRequest): Promise<proto.cline.String> {
		return BrowserServiceClient.makeUnaryRequest(
			"relaunchChromeDebugMode",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.String.fromJSON,
		)
	}
}
export class CheckpointsServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.CheckpointsService"
	static async checkpointRestore(request: proto.cline.CheckpointRestoreRequest): Promise<proto.cline.Empty> {
		return CheckpointsServiceClient.makeUnaryRequest(
			"checkpointRestore",
			request,
			proto.cline.CheckpointRestoreRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
}
export class CodebaseMemoryServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.CodebaseMemoryService"
	static async getStatus(request: proto.cline.EmptyRequest): Promise<proto.cline.CodebaseMemoryStatus> {
		return CodebaseMemoryServiceClient.makeUnaryRequest(
			"getStatus",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.CodebaseMemoryStatus.fromJSON,
		)
	}
	static indexProject(
		request: proto.cline.IndexProjectRequest,
		callbacks: Callbacks<proto.cline.IndexProgressEvent>,
		options?: StreamingOptions,
	): () => void {
		return CodebaseMemoryServiceClient.makeStreamingRequest(
			"indexProject",
			request,
			proto.cline.IndexProjectRequest.toJSON,
			proto.cline.IndexProgressEvent.fromJSON,
			callbacks,
			options,
		)
	}
	static reindexProject(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.IndexProgressEvent>,
		options?: StreamingOptions,
	): () => void {
		return CodebaseMemoryServiceClient.makeStreamingRequest(
			"reindexProject",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.IndexProgressEvent.fromJSON,
			callbacks,
			options,
		)
	}
	static downloadBinary(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.IndexProgressEvent>,
		options?: StreamingOptions,
	): () => void {
		return CodebaseMemoryServiceClient.makeStreamingRequest(
			"downloadBinary",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.IndexProgressEvent.fromJSON,
			callbacks,
			options,
		)
	}
	static async viewGraph(request: proto.cline.EmptyRequest): Promise<proto.cline.ViewGraphResponse> {
		return CodebaseMemoryServiceClient.makeUnaryRequest(
			"viewGraph",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.ViewGraphResponse.fromJSON,
		)
	}
	static async stopGraphServer(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return CodebaseMemoryServiceClient.makeUnaryRequest(
			"stopGraphServer",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async listTools(request: proto.cline.EmptyRequest): Promise<proto.cline.CodebaseMemoryTools> {
		return CodebaseMemoryServiceClient.makeUnaryRequest(
			"listTools",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.CodebaseMemoryTools.fromJSON,
		)
	}
}
export class CommandsServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.CommandsService"
	static async addToCline(request: proto.cline.CommandContext): Promise<proto.cline.Empty> {
		return CommandsServiceClient.makeUnaryRequest(
			"addToCline",
			request,
			proto.cline.CommandContext.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async fixWithCline(request: proto.cline.CommandContext): Promise<proto.cline.Empty> {
		return CommandsServiceClient.makeUnaryRequest(
			"fixWithCline",
			request,
			proto.cline.CommandContext.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async explainWithCline(request: proto.cline.CommandContext): Promise<proto.cline.Empty> {
		return CommandsServiceClient.makeUnaryRequest(
			"explainWithCline",
			request,
			proto.cline.CommandContext.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async improveWithCline(request: proto.cline.CommandContext): Promise<proto.cline.Empty> {
		return CommandsServiceClient.makeUnaryRequest(
			"improveWithCline",
			request,
			proto.cline.CommandContext.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
}
export class DocsIndexServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.DocsIndexService"
	static async ping(request: proto.cline.PingRequest): Promise<proto.cline.PingResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"ping",
			request,
			proto.cline.PingRequest.toJSON,
			proto.cline.PingResponse.fromJSON,
		)
	}
	static async listProjects(request: proto.cline.ListProjectsRequest): Promise<proto.cline.ListProjectsResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"listProjects",
			request,
			proto.cline.ListProjectsRequest.toJSON,
			proto.cline.ListProjectsResponse.fromJSON,
		)
	}
	static async createProject(request: proto.cline.CreateProjectRequest): Promise<proto.cline.CreateProjectResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"createProject",
			request,
			proto.cline.CreateProjectRequest.toJSON,
			proto.cline.CreateProjectResponse.fromJSON,
		)
	}
	static async renameProject(request: proto.cline.RenameProjectRequest): Promise<proto.cline.ProjectMutationResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"renameProject",
			request,
			proto.cline.RenameProjectRequest.toJSON,
			proto.cline.ProjectMutationResponse.fromJSON,
		)
	}
	static async deleteProject(request: proto.cline.DeleteProjectRequest): Promise<proto.cline.ProjectMutationResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"deleteProject",
			request,
			proto.cline.DeleteProjectRequest.toJSON,
			proto.cline.ProjectMutationResponse.fromJSON,
		)
	}
	static async uploadFile(request: proto.cline.UploadFileRequest): Promise<proto.cline.UploadFileResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"uploadFile",
			request,
			proto.cline.UploadFileRequest.toJSON,
			proto.cline.UploadFileResponse.fromJSON,
		)
	}
	static async indexUrl(request: proto.cline.IndexUrlRequest): Promise<proto.cline.IndexUrlResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"indexUrl",
			request,
			proto.cline.IndexUrlRequest.toJSON,
			proto.cline.IndexUrlResponse.fromJSON,
		)
	}
	static async indexBatch(request: proto.cline.IndexBatchRequest): Promise<proto.cline.IndexBatchResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"indexBatch",
			request,
			proto.cline.IndexBatchRequest.toJSON,
			proto.cline.IndexBatchResponse.fromJSON,
		)
	}
	static async getTask(request: proto.cline.TaskStatusRequest): Promise<proto.cline.TaskStatusResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"getTask",
			request,
			proto.cline.TaskStatusRequest.toJSON,
			proto.cline.TaskStatusResponse.fromJSON,
		)
	}
	static async searchDocuments(request: proto.cline.SearchDocumentsRequest): Promise<proto.cline.SearchDocumentsResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"searchDocuments",
			request,
			proto.cline.SearchDocumentsRequest.toJSON,
			proto.cline.SearchDocumentsResponse.fromJSON,
		)
	}
	static async deleteDocument(request: proto.cline.DeleteDocumentRequest): Promise<proto.cline.DeleteDocumentResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"deleteDocument",
			request,
			proto.cline.DeleteDocumentRequest.toJSON,
			proto.cline.DeleteDocumentResponse.fromJSON,
		)
	}
	static async listDocuments(request: proto.cline.ListDocumentsRequest): Promise<proto.cline.ListDocumentsResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"listDocuments",
			request,
			proto.cline.ListDocumentsRequest.toJSON,
			proto.cline.ListDocumentsResponse.fromJSON,
		)
	}
	static async indexCodebase(request: proto.cline.IndexCodebaseRequest): Promise<proto.cline.IndexCodebaseResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"indexCodebase",
			request,
			proto.cline.IndexCodebaseRequest.toJSON,
			proto.cline.IndexCodebaseResponse.fromJSON,
		)
	}
	static async startCodebaseWatch(request: proto.cline.StartCodebaseWatchRequest): Promise<proto.cline.CodebaseWatchStatus> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"startCodebaseWatch",
			request,
			proto.cline.StartCodebaseWatchRequest.toJSON,
			proto.cline.CodebaseWatchStatus.fromJSON,
		)
	}
	static async getCodebaseWatch(request: proto.cline.GetCodebaseWatchRequest): Promise<proto.cline.CodebaseWatchStatus> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"getCodebaseWatch",
			request,
			proto.cline.GetCodebaseWatchRequest.toJSON,
			proto.cline.CodebaseWatchStatus.fromJSON,
		)
	}
	static async stopCodebaseWatch(request: proto.cline.GetCodebaseWatchRequest): Promise<proto.cline.CodebaseWatchStatus> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"stopCodebaseWatch",
			request,
			proto.cline.GetCodebaseWatchRequest.toJSON,
			proto.cline.CodebaseWatchStatus.fromJSON,
		)
	}
	static async listCodebaseTools(request: proto.cline.ListCodebaseToolsRequest): Promise<proto.cline.CodebaseToolCatalog> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"listCodebaseTools",
			request,
			proto.cline.ListCodebaseToolsRequest.toJSON,
			proto.cline.CodebaseToolCatalog.fromJSON,
		)
	}
	static async listDocsIndexTools(request: proto.cline.EmptyRequest): Promise<proto.cline.DocsIndexTools> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"listDocsIndexTools",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.DocsIndexTools.fromJSON,
		)
	}
	static async registerMcpServer(request: proto.cline.RegisterMcpRequest): Promise<proto.cline.Empty> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"registerMcpServer",
			request,
			proto.cline.RegisterMcpRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async unregisterMcpServer(request: proto.cline.UnregisterMcpRequest): Promise<proto.cline.Empty> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"unregisterMcpServer",
			request,
			proto.cline.UnregisterMcpRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async getDocsIndexSettings(request: proto.cline.EmptyRequest): Promise<proto.cline.GetDocsIndexSettingsResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"getDocsIndexSettings",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.GetDocsIndexSettingsResponse.fromJSON,
		)
	}
	static async updateDocsIndexSettings(
		request: proto.cline.UpdateDocsIndexSettingsRequest,
	): Promise<proto.cline.UpdateDocsIndexSettingsResponse> {
		return DocsIndexServiceClient.makeUnaryRequest(
			"updateDocsIndexSettings",
			request,
			proto.cline.UpdateDocsIndexSettingsRequest.toJSON,
			proto.cline.UpdateDocsIndexSettingsResponse.fromJSON,
		)
	}
}
export class FileServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.FileService"
	static async copyToClipboard(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"copyToClipboard",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async openFile(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openFile",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async openImage(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openImage",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async openMention(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openMention",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async deleteRuleFile(request: proto.cline.RuleFileRequest): Promise<proto.cline.RuleFile> {
		return FileServiceClient.makeUnaryRequest(
			"deleteRuleFile",
			request,
			proto.cline.RuleFileRequest.toJSON,
			proto.cline.RuleFile.fromJSON,
		)
	}
	static async createRuleFile(request: proto.cline.RuleFileRequest): Promise<proto.cline.RuleFile> {
		return FileServiceClient.makeUnaryRequest(
			"createRuleFile",
			request,
			proto.cline.RuleFileRequest.toJSON,
			proto.cline.RuleFile.fromJSON,
		)
	}
	static async searchCommits(request: proto.cline.StringRequest): Promise<proto.cline.GitCommits> {
		return FileServiceClient.makeUnaryRequest(
			"searchCommits",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.GitCommits.fromJSON,
		)
	}
	static async selectFiles(request: proto.cline.BooleanRequest): Promise<proto.cline.StringArrays> {
		return FileServiceClient.makeUnaryRequest(
			"selectFiles",
			request,
			proto.cline.BooleanRequest.toJSON,
			proto.cline.StringArrays.fromJSON,
		)
	}
	static async getRelativePaths(request: proto.cline.RelativePathsRequest): Promise<proto.cline.RelativePaths> {
		return FileServiceClient.makeUnaryRequest(
			"getRelativePaths",
			request,
			proto.cline.RelativePathsRequest.toJSON,
			proto.cline.RelativePaths.fromJSON,
		)
	}
	static async searchFiles(request: proto.cline.FileSearchRequest): Promise<proto.cline.FileSearchResults> {
		return FileServiceClient.makeUnaryRequest(
			"searchFiles",
			request,
			proto.cline.FileSearchRequest.toJSON,
			proto.cline.FileSearchResults.fromJSON,
		)
	}
	static async toggleClineRule(request: proto.cline.ToggleClineRuleRequest): Promise<proto.cline.ToggleClineRules> {
		return FileServiceClient.makeUnaryRequest(
			"toggleClineRule",
			request,
			proto.cline.ToggleClineRuleRequest.toJSON,
			proto.cline.ToggleClineRules.fromJSON,
		)
	}
	static async toggleCursorRule(request: proto.cline.ToggleCursorRuleRequest): Promise<proto.cline.ClineRulesToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleCursorRule",
			request,
			proto.cline.ToggleCursorRuleRequest.toJSON,
			proto.cline.ClineRulesToggles.fromJSON,
		)
	}
	static async toggleWindsurfRule(request: proto.cline.ToggleWindsurfRuleRequest): Promise<proto.cline.ClineRulesToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleWindsurfRule",
			request,
			proto.cline.ToggleWindsurfRuleRequest.toJSON,
			proto.cline.ClineRulesToggles.fromJSON,
		)
	}
	static async toggleAgentsRule(request: proto.cline.ToggleAgentsRuleRequest): Promise<proto.cline.ClineRulesToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleAgentsRule",
			request,
			proto.cline.ToggleAgentsRuleRequest.toJSON,
			proto.cline.ClineRulesToggles.fromJSON,
		)
	}
	static async refreshRules(request: proto.cline.EmptyRequest): Promise<proto.cline.RefreshedRules> {
		return FileServiceClient.makeUnaryRequest(
			"refreshRules",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.RefreshedRules.fromJSON,
		)
	}
	static async openDiskConversationHistory(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openDiskConversationHistory",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async toggleWorkflow(request: proto.cline.ToggleWorkflowRequest): Promise<proto.cline.ClineRulesToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleWorkflow",
			request,
			proto.cline.ToggleWorkflowRequest.toJSON,
			proto.cline.ClineRulesToggles.fromJSON,
		)
	}
	static async ifFileExistsRelativePath(request: proto.cline.StringRequest): Promise<proto.cline.BooleanResponse> {
		return FileServiceClient.makeUnaryRequest(
			"ifFileExistsRelativePath",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.BooleanResponse.fromJSON,
		)
	}
	static async openFileRelativePath(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openFileRelativePath",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async openFocusChainFile(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return FileServiceClient.makeUnaryRequest(
			"openFocusChainFile",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async refreshHooks(request: proto.cline.EmptyRequest): Promise<proto.cline.HooksToggles> {
		return FileServiceClient.makeUnaryRequest(
			"refreshHooks",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.HooksToggles.fromJSON,
		)
	}
	static async toggleHook(request: proto.cline.ToggleHookRequest): Promise<proto.cline.ToggleHookResponse> {
		return FileServiceClient.makeUnaryRequest(
			"toggleHook",
			request,
			proto.cline.ToggleHookRequest.toJSON,
			proto.cline.ToggleHookResponse.fromJSON,
		)
	}
	static async createHook(request: proto.cline.CreateHookRequest): Promise<proto.cline.CreateHookResponse> {
		return FileServiceClient.makeUnaryRequest(
			"createHook",
			request,
			proto.cline.CreateHookRequest.toJSON,
			proto.cline.CreateHookResponse.fromJSON,
		)
	}
	static async deleteHook(request: proto.cline.DeleteHookRequest): Promise<proto.cline.DeleteHookResponse> {
		return FileServiceClient.makeUnaryRequest(
			"deleteHook",
			request,
			proto.cline.DeleteHookRequest.toJSON,
			proto.cline.DeleteHookResponse.fromJSON,
		)
	}
	static async refreshSkills(request: proto.cline.EmptyRequest): Promise<proto.cline.RefreshedSkills> {
		return FileServiceClient.makeUnaryRequest(
			"refreshSkills",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.RefreshedSkills.fromJSON,
		)
	}
	static async toggleSkill(request: proto.cline.ToggleSkillRequest): Promise<proto.cline.SkillsToggles> {
		return FileServiceClient.makeUnaryRequest(
			"toggleSkill",
			request,
			proto.cline.ToggleSkillRequest.toJSON,
			proto.cline.SkillsToggles.fromJSON,
		)
	}
	static async createSkillFile(request: proto.cline.CreateSkillRequest): Promise<proto.cline.SkillsToggles> {
		return FileServiceClient.makeUnaryRequest(
			"createSkillFile",
			request,
			proto.cline.CreateSkillRequest.toJSON,
			proto.cline.SkillsToggles.fromJSON,
		)
	}
	static async deleteSkillFile(request: proto.cline.DeleteSkillRequest): Promise<proto.cline.SkillsToggles> {
		return FileServiceClient.makeUnaryRequest(
			"deleteSkillFile",
			request,
			proto.cline.DeleteSkillRequest.toJSON,
			proto.cline.SkillsToggles.fromJSON,
		)
	}
}
export class MarketplaceServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.MarketplaceService"
	static async getMarketplaceCatalog(request: proto.cline.EmptyRequest): Promise<proto.cline.MarketplaceCatalog> {
		return MarketplaceServiceClient.makeUnaryRequest(
			"getMarketplaceCatalog",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.MarketplaceCatalog.fromJSON,
		)
	}
	static async listMarketplaceLocalInstalledEntries(
		request: proto.cline.EmptyRequest,
	): Promise<proto.cline.MarketplaceLocalInstalledEntries> {
		return MarketplaceServiceClient.makeUnaryRequest(
			"listMarketplaceLocalInstalledEntries",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.MarketplaceLocalInstalledEntries.fromJSON,
		)
	}
	static async listMarketplaceInstalledEntries(
		request: proto.cline.MarketplaceEntriesRequest,
	): Promise<proto.cline.MarketplaceInstalledEntries> {
		return MarketplaceServiceClient.makeUnaryRequest(
			"listMarketplaceInstalledEntries",
			request,
			proto.cline.MarketplaceEntriesRequest.toJSON,
			proto.cline.MarketplaceInstalledEntries.fromJSON,
		)
	}
	static async installMarketplaceEntry(
		request: proto.cline.MarketplaceEntryRequest,
	): Promise<proto.cline.MarketplaceInstallResult> {
		return MarketplaceServiceClient.makeUnaryRequest(
			"installMarketplaceEntry",
			request,
			proto.cline.MarketplaceEntryRequest.toJSON,
			proto.cline.MarketplaceInstallResult.fromJSON,
		)
	}
	static async uninstallMarketplaceEntry(
		request: proto.cline.MarketplaceEntryRequest,
	): Promise<proto.cline.MarketplaceInstallResult> {
		return MarketplaceServiceClient.makeUnaryRequest(
			"uninstallMarketplaceEntry",
			request,
			proto.cline.MarketplaceEntryRequest.toJSON,
			proto.cline.MarketplaceInstallResult.fromJSON,
		)
	}
	static async toggleMarketplaceLocalInstalledEntry(
		request: proto.cline.ToggleMarketplaceLocalInstalledEntryRequest,
	): Promise<proto.cline.MarketplaceLocalInstalledEntries> {
		return MarketplaceServiceClient.makeUnaryRequest(
			"toggleMarketplaceLocalInstalledEntry",
			request,
			proto.cline.ToggleMarketplaceLocalInstalledEntryRequest.toJSON,
			proto.cline.MarketplaceLocalInstalledEntries.fromJSON,
		)
	}
	static async uninstallMarketplaceLocalInstalledEntry(
		request: proto.cline.MarketplaceLocalInstalledEntryRequest,
	): Promise<proto.cline.MarketplaceInstallResult> {
		return MarketplaceServiceClient.makeUnaryRequest(
			"uninstallMarketplaceLocalInstalledEntry",
			request,
			proto.cline.MarketplaceLocalInstalledEntryRequest.toJSON,
			proto.cline.MarketplaceInstallResult.fromJSON,
		)
	}
}
export class McpServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.McpService"
	static async toggleMcpServer(request: proto.cline.ToggleMcpServerRequest): Promise<proto.cline.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"toggleMcpServer",
			request,
			proto.cline.ToggleMcpServerRequest.toJSON,
			proto.cline.McpServers.fromJSON,
		)
	}
	static async updateMcpTimeout(request: proto.cline.UpdateMcpTimeoutRequest): Promise<proto.cline.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"updateMcpTimeout",
			request,
			proto.cline.UpdateMcpTimeoutRequest.toJSON,
			proto.cline.McpServers.fromJSON,
		)
	}
	static async addRemoteMcpServer(request: proto.cline.AddRemoteMcpServerRequest): Promise<proto.cline.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"addRemoteMcpServer",
			request,
			proto.cline.AddRemoteMcpServerRequest.toJSON,
			proto.cline.McpServers.fromJSON,
		)
	}
	static async addStdioMcpServer(request: proto.cline.AddStdioMcpServerRequest): Promise<proto.cline.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"addStdioMcpServer",
			request,
			proto.cline.AddStdioMcpServerRequest.toJSON,
			proto.cline.McpServers.fromJSON,
		)
	}
	static async restartMcpServer(request: proto.cline.StringRequest): Promise<proto.cline.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"restartMcpServer",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.McpServers.fromJSON,
		)
	}
	static async deleteMcpServer(request: proto.cline.StringRequest): Promise<proto.cline.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"deleteMcpServer",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.McpServers.fromJSON,
		)
	}
	static async toggleToolAutoApprove(request: proto.cline.ToggleToolAutoApproveRequest): Promise<proto.cline.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"toggleToolAutoApprove",
			request,
			proto.cline.ToggleToolAutoApproveRequest.toJSON,
			proto.cline.McpServers.fromJSON,
		)
	}
	static async openMcpSettings(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return McpServiceClient.makeUnaryRequest(
			"openMcpSettings",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async authenticateMcpServer(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return McpServiceClient.makeUnaryRequest(
			"authenticateMcpServer",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async getLatestMcpServers(request: proto.cline.Empty): Promise<proto.cline.McpServers> {
		return McpServiceClient.makeUnaryRequest(
			"getLatestMcpServers",
			request,
			proto.cline.Empty.toJSON,
			proto.cline.McpServers.fromJSON,
		)
	}
	static subscribeToMcpServers(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.McpServers>,
		options?: StreamingOptions,
	): () => void {
		return McpServiceClient.makeStreamingRequest(
			"subscribeToMcpServers",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.McpServers.fromJSON,
			callbacks,
			options,
		)
	}
}
export class ModelsServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.ModelsService"
	static async getOllamaModels(request: proto.cline.StringRequest): Promise<proto.cline.StringArray> {
		return ModelsServiceClient.makeUnaryRequest(
			"getOllamaModels",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.StringArray.fromJSON,
		)
	}
	static async getLmStudioModels(request: proto.cline.StringRequest): Promise<proto.cline.StringArray> {
		return ModelsServiceClient.makeUnaryRequest(
			"getLmStudioModels",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.StringArray.fromJSON,
		)
	}
	static async getVsCodeLmModels(request: proto.cline.EmptyRequest): Promise<proto.cline.VsCodeLmModelsArray> {
		return ModelsServiceClient.makeUnaryRequest(
			"getVsCodeLmModels",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.VsCodeLmModelsArray.fromJSON,
		)
	}
	static async refreshOpenRouterModelsRpc(
		request: proto.cline.EmptyRequest,
	): Promise<proto.cline.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshOpenRouterModelsRpc",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshClineRecommendedModelsRpc(
		request: proto.cline.EmptyRequest,
	): Promise<proto.cline.ClineRecommendedModelsResponse> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshClineRecommendedModelsRpc",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.ClineRecommendedModelsResponse.fromJSON,
		)
	}
	static async refreshHuggingFaceModels(request: proto.cline.EmptyRequest): Promise<proto.cline.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshHuggingFaceModels",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshOpenAiModels(request: proto.cline.OpenAiModelsRequest): Promise<proto.cline.StringArray> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshOpenAiModels",
			request,
			proto.cline.OpenAiModelsRequest.toJSON,
			proto.cline.StringArray.fromJSON,
		)
	}
	static async refreshRequestyModels(request: proto.cline.EmptyRequest): Promise<proto.cline.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshRequestyModels",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshHicapModels(request: proto.cline.EmptyRequest): Promise<proto.cline.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshHicapModels",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshLiteLlmModelsRpc(request: proto.cline.EmptyRequest): Promise<proto.cline.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshLiteLlmModelsRpc",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static subscribeToOpenRouterModels(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.OpenRouterCompatibleModelInfo>,
		options?: StreamingOptions,
	): () => void {
		return ModelsServiceClient.makeStreamingRequest(
			"subscribeToOpenRouterModels",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToLiteLlmModels(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.OpenRouterCompatibleModelInfo>,
		options?: StreamingOptions,
	): () => void {
		return ModelsServiceClient.makeStreamingRequest(
			"subscribeToLiteLlmModels",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
			callbacks,
			options,
		)
	}
	static async updateApiConfigurationProto(request: proto.cline.UpdateApiConfigurationRequest): Promise<proto.cline.Empty> {
		return ModelsServiceClient.makeUnaryRequest(
			"updateApiConfigurationProto",
			request,
			proto.cline.UpdateApiConfigurationRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async updateApiConfiguration(request: proto.cline.UpdateApiConfigurationRequestNew): Promise<proto.cline.Empty> {
		return ModelsServiceClient.makeUnaryRequest(
			"updateApiConfiguration",
			request,
			proto.cline.UpdateApiConfigurationRequestNew.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async updateApiConfigurationPartial(
		request: proto.cline.UpdateApiConfigurationPartialRequest,
	): Promise<proto.cline.Empty> {
		return ModelsServiceClient.makeUnaryRequest(
			"updateApiConfigurationPartial",
			request,
			proto.cline.UpdateApiConfigurationPartialRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async refreshGroqModelsRpc(request: proto.cline.EmptyRequest): Promise<proto.cline.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshGroqModelsRpc",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshBasetenModelsRpc(request: proto.cline.EmptyRequest): Promise<proto.cline.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshBasetenModelsRpc",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async getSapAiCoreModels(request: proto.cline.SapAiCoreModelsRequest): Promise<proto.cline.SapAiCoreModelsResponse> {
		return ModelsServiceClient.makeUnaryRequest(
			"getSapAiCoreModels",
			request,
			proto.cline.SapAiCoreModelsRequest.toJSON,
			proto.cline.SapAiCoreModelsResponse.fromJSON,
		)
	}
	static async refreshOcaModels(request: proto.cline.StringRequest): Promise<proto.cline.OcaCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshOcaModels",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.OcaCompatibleModelInfo.fromJSON,
		)
	}
	static async getAihubmixModels(request: proto.cline.EmptyRequest): Promise<proto.cline.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"getAihubmixModels",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshVercelAiGatewayModelsRpc(
		request: proto.cline.EmptyRequest,
	): Promise<proto.cline.OpenRouterCompatibleModelInfo> {
		return ModelsServiceClient.makeUnaryRequest(
			"refreshVercelAiGatewayModelsRpc",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async listProviders(request: proto.cline.Empty): Promise<proto.cline.ProviderListingsResponse> {
		return ModelsServiceClient.makeUnaryRequest(
			"listProviders",
			request,
			proto.cline.Empty.toJSON,
			proto.cline.ProviderListingsResponse.fromJSON,
		)
	}
	static async resolveProviderModels(
		request: proto.cline.ResolveProviderModelsRequest,
	): Promise<proto.cline.ProviderModelsResponse> {
		return ModelsServiceClient.makeUnaryRequest(
			"resolveProviderModels",
			request,
			proto.cline.ResolveProviderModelsRequest.toJSON,
			proto.cline.ProviderModelsResponse.fromJSON,
		)
	}
	static async resolveModelInfo(request: proto.cline.ResolveModelInfoRequest): Promise<proto.cline.ResolveModelInfoResponse> {
		return ModelsServiceClient.makeUnaryRequest(
			"resolveModelInfo",
			request,
			proto.cline.ResolveModelInfoRequest.toJSON,
			proto.cline.ResolveModelInfoResponse.fromJSON,
		)
	}
	static async readProviderConfig(request: proto.cline.StringRequest): Promise<proto.cline.ProviderConfigResponse> {
		return ModelsServiceClient.makeUnaryRequest(
			"readProviderConfig",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.ProviderConfigResponse.fromJSON,
		)
	}
	static async writeProviderConfig(
		request: proto.cline.WriteProviderConfigRequest,
	): Promise<proto.cline.ProviderConfigResponse> {
		return ModelsServiceClient.makeUnaryRequest(
			"writeProviderConfig",
			request,
			proto.cline.WriteProviderConfigRequest.toJSON,
			proto.cline.ProviderConfigResponse.fromJSON,
		)
	}
	static async commitModelSelection(request: proto.cline.CommitModelSelectionRequest): Promise<proto.cline.Empty> {
		return ModelsServiceClient.makeUnaryRequest(
			"commitModelSelection",
			request,
			proto.cline.CommitModelSelectionRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
}
export class OcaAccountServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.OcaAccountService"
	static async ocaAccountLoginClicked(request: proto.cline.EmptyRequest): Promise<proto.cline.String> {
		return OcaAccountServiceClient.makeUnaryRequest(
			"ocaAccountLoginClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.String.fromJSON,
		)
	}
	static async ocaAccountLogoutClicked(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return OcaAccountServiceClient.makeUnaryRequest(
			"ocaAccountLogoutClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static ocaSubscribeToAuthStatusUpdate(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.OcaAuthState>,
		options?: StreamingOptions,
	): () => void {
		return OcaAccountServiceClient.makeStreamingRequest(
			"ocaSubscribeToAuthStatusUpdate",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.OcaAuthState.fromJSON,
			callbacks,
			options,
		)
	}
}
export class RemoteConfigServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.RemoteConfigService"
	static async getRemoteConfigSettings(request: proto.cline.Empty): Promise<proto.cline.RemoteConfigSettingsResponse> {
		return RemoteConfigServiceClient.makeUnaryRequest(
			"getRemoteConfigSettings",
			request,
			proto.cline.Empty.toJSON,
			proto.cline.RemoteConfigSettingsResponse.fromJSON,
		)
	}
	static async toggleRemoteConfigSetting(request: proto.cline.StringRequest): Promise<proto.cline.RemoteConfigSetting> {
		return RemoteConfigServiceClient.makeUnaryRequest(
			"toggleRemoteConfigSetting",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.RemoteConfigSetting.fromJSON,
		)
	}
}
export class SlashServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.SlashService"
	static async reportBug(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return SlashServiceClient.makeUnaryRequest(
			"reportBug",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async condense(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return SlashServiceClient.makeUnaryRequest(
			"condense",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async getAvailableSlashCommands(request: proto.cline.EmptyRequest): Promise<proto.cline.SlashCommandsResponse> {
		return SlashServiceClient.makeUnaryRequest(
			"getAvailableSlashCommands",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.SlashCommandsResponse.fromJSON,
		)
	}
}
export class StateServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.StateService"
	static async getLatestState(request: proto.cline.EmptyRequest): Promise<proto.cline.State> {
		return StateServiceClient.makeUnaryRequest(
			"getLatestState",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.State.fromJSON,
		)
	}
	static async updateTerminalConnectionTimeout(
		request: proto.cline.UpdateTerminalConnectionTimeoutRequest,
	): Promise<proto.cline.UpdateTerminalConnectionTimeoutResponse> {
		return StateServiceClient.makeUnaryRequest(
			"updateTerminalConnectionTimeout",
			request,
			proto.cline.UpdateTerminalConnectionTimeoutRequest.toJSON,
			proto.cline.UpdateTerminalConnectionTimeoutResponse.fromJSON,
		)
	}
	static async updateTerminalReuseEnabled(request: proto.cline.BooleanRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateTerminalReuseEnabled",
			request,
			proto.cline.BooleanRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async getAvailableTerminalProfiles(request: proto.cline.EmptyRequest): Promise<proto.cline.TerminalProfiles> {
		return StateServiceClient.makeUnaryRequest(
			"getAvailableTerminalProfiles",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.TerminalProfiles.fromJSON,
		)
	}
	static subscribeToState(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.State>,
		options?: StreamingOptions,
	): () => void {
		return StateServiceClient.makeStreamingRequest(
			"subscribeToState",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.State.fromJSON,
			callbacks,
			options,
		)
	}
	static async toggleFavoriteModel(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"toggleFavoriteModel",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async resetState(request: proto.cline.ResetStateRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"resetState",
			request,
			proto.cline.ResetStateRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async togglePlanActModeProto(request: proto.cline.TogglePlanActModeRequest): Promise<proto.cline.Boolean> {
		return StateServiceClient.makeUnaryRequest(
			"togglePlanActModeProto",
			request,
			proto.cline.TogglePlanActModeRequest.toJSON,
			proto.cline.Boolean.fromJSON,
		)
	}
	static async updateAutoApprovalSettings(request: proto.cline.AutoApprovalSettingsRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateAutoApprovalSettings",
			request,
			proto.cline.AutoApprovalSettingsRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async updateSettings(request: proto.cline.UpdateSettingsRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateSettings",
			request,
			proto.cline.UpdateSettingsRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async updateSettingsCli(request: proto.cline.UpdateSettingsRequestCli): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateSettingsCli",
			request,
			proto.cline.UpdateSettingsRequestCli.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async updateTaskSettings(request: proto.cline.UpdateTaskSettingsRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateTaskSettings",
			request,
			proto.cline.UpdateTaskSettingsRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async updateTelemetrySetting(request: proto.cline.TelemetrySettingRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateTelemetrySetting",
			request,
			proto.cline.TelemetrySettingRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async captureOnboardingProgress(request: proto.cline.OnboardingProgressRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"captureOnboardingProgress",
			request,
			proto.cline.OnboardingProgressRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async setWelcomeViewCompleted(request: proto.cline.BooleanRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"setWelcomeViewCompleted",
			request,
			proto.cline.BooleanRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async updateInfoBannerVersion(request: proto.cline.Int64Request): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateInfoBannerVersion",
			request,
			proto.cline.Int64Request.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async updateModelBannerVersion(request: proto.cline.Int64Request): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateModelBannerVersion",
			request,
			proto.cline.Int64Request.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async updateCliBannerVersion(request: proto.cline.Int64Request): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"updateCliBannerVersion",
			request,
			proto.cline.Int64Request.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async dismissBanner(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"dismissBanner",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async trackBannerEvent(request: proto.cline.TrackBannerEventRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"trackBannerEvent",
			request,
			proto.cline.TrackBannerEventRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async installClineCli(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"installClineCli",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async checkCliInstallation(request: proto.cline.EmptyRequest): Promise<proto.cline.Boolean> {
		return StateServiceClient.makeUnaryRequest(
			"checkCliInstallation",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Boolean.fromJSON,
		)
	}
	static async getProcessInfo(request: proto.cline.EmptyRequest): Promise<proto.cline.ProcessInfo> {
		return StateServiceClient.makeUnaryRequest(
			"getProcessInfo",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.ProcessInfo.fromJSON,
		)
	}
	static async flushPendingState(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"flushPendingState",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async refreshRemoteConfig(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return StateServiceClient.makeUnaryRequest(
			"refreshRemoteConfig",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async testOtelConnection(request: proto.cline.EmptyRequest): Promise<proto.cline.TestConnectionResult> {
		return StateServiceClient.makeUnaryRequest(
			"testOtelConnection",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.TestConnectionResult.fromJSON,
		)
	}
	static async testPromptUploading(request: proto.cline.EmptyRequest): Promise<proto.cline.TestConnectionResult> {
		return StateServiceClient.makeUnaryRequest(
			"testPromptUploading",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.TestConnectionResult.fromJSON,
		)
	}
	static async getProfiles(request: proto.cline.EmptyRequest): Promise<proto.cline.ProfilesResponse> {
		return StateServiceClient.makeUnaryRequest(
			"getProfiles",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.ProfilesResponse.fromJSON,
		)
	}
	static async upsertProfile(request: proto.cline.UpsertProfileRequest): Promise<proto.cline.ProfilesResponse> {
		return StateServiceClient.makeUnaryRequest(
			"upsertProfile",
			request,
			proto.cline.UpsertProfileRequest.toJSON,
			proto.cline.ProfilesResponse.fromJSON,
		)
	}
	static async setActiveProfile(request: proto.cline.SetActiveProfileRequest): Promise<proto.cline.ProfilesResponse> {
		return StateServiceClient.makeUnaryRequest(
			"setActiveProfile",
			request,
			proto.cline.SetActiveProfileRequest.toJSON,
			proto.cline.ProfilesResponse.fromJSON,
		)
	}
	static async deleteProfile(request: proto.cline.DeleteProfileRequest): Promise<proto.cline.ProfilesResponse> {
		return StateServiceClient.makeUnaryRequest(
			"deleteProfile",
			request,
			proto.cline.DeleteProfileRequest.toJSON,
			proto.cline.ProfilesResponse.fromJSON,
		)
	}
}
export class TaskServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.TaskService"
	static async cancelTask(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"cancelTask",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async cancelQueuedPrompt(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"cancelQueuedPrompt",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async cancelBackgroundCommand(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"cancelBackgroundCommand",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async clearTask(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"clearTask",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async getTotalTasksSize(request: proto.cline.EmptyRequest): Promise<proto.cline.Int64> {
		return TaskServiceClient.makeUnaryRequest(
			"getTotalTasksSize",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Int64.fromJSON,
		)
	}
	static async deleteTasksWithIds(request: proto.cline.StringArrayRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"deleteTasksWithIds",
			request,
			proto.cline.StringArrayRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async newTask(request: proto.cline.NewTaskRequest): Promise<proto.cline.String> {
		return TaskServiceClient.makeUnaryRequest(
			"newTask",
			request,
			proto.cline.NewTaskRequest.toJSON,
			proto.cline.String.fromJSON,
		)
	}
	static async showTaskWithId(request: proto.cline.StringRequest): Promise<proto.cline.TaskResponse> {
		return TaskServiceClient.makeUnaryRequest(
			"showTaskWithId",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.TaskResponse.fromJSON,
		)
	}
	static async exportTaskWithId(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"exportTaskWithId",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async toggleTaskFavorite(request: proto.cline.TaskFavoriteRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"toggleTaskFavorite",
			request,
			proto.cline.TaskFavoriteRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async getTaskHistory(request: proto.cline.GetTaskHistoryRequest): Promise<proto.cline.TaskHistoryArray> {
		return TaskServiceClient.makeUnaryRequest(
			"getTaskHistory",
			request,
			proto.cline.GetTaskHistoryRequest.toJSON,
			proto.cline.TaskHistoryArray.fromJSON,
		)
	}
	static async askResponse(request: proto.cline.AskResponseRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"askResponse",
			request,
			proto.cline.AskResponseRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async editMessageAndRegenerate(request: proto.cline.EditMessageAndRegenerateRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"editMessageAndRegenerate",
			request,
			proto.cline.EditMessageAndRegenerateRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async taskFeedback(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"taskFeedback",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async executeQuickWin(request: proto.cline.ExecuteQuickWinRequest): Promise<proto.cline.Empty> {
		return TaskServiceClient.makeUnaryRequest(
			"executeQuickWin",
			request,
			proto.cline.ExecuteQuickWinRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async deleteAllTaskHistory(request: proto.cline.EmptyRequest): Promise<proto.cline.DeleteAllTaskHistoryCount> {
		return TaskServiceClient.makeUnaryRequest(
			"deleteAllTaskHistory",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.DeleteAllTaskHistoryCount.fromJSON,
		)
	}
}
export class UiServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.UiService"
	static async scrollToSettings(request: proto.cline.StringRequest): Promise<proto.cline.KeyValuePair> {
		return UiServiceClient.makeUnaryRequest(
			"scrollToSettings",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.KeyValuePair.fromJSON,
		)
	}
	static async setTerminalExecutionMode(request: proto.cline.BooleanRequest): Promise<proto.cline.KeyValuePair> {
		return UiServiceClient.makeUnaryRequest(
			"setTerminalExecutionMode",
			request,
			proto.cline.BooleanRequest.toJSON,
			proto.cline.KeyValuePair.fromJSON,
		)
	}
	static async onDidShowAnnouncement(request: proto.cline.EmptyRequest): Promise<proto.cline.Boolean> {
		return UiServiceClient.makeUnaryRequest(
			"onDidShowAnnouncement",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Boolean.fromJSON,
		)
	}
	static subscribeToAddToInput(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.String>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToAddToInput",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.String.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToMcpButtonClicked(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.Empty>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToMcpButtonClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToMarketplaceButtonClicked(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.Empty>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToMarketplaceButtonClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToHistoryButtonClicked(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.Empty>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToHistoryButtonClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToChatButtonClicked(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.Empty>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToChatButtonClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToAccountButtonClicked(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.Empty>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToAccountButtonClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToSettingsButtonClicked(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.Empty>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToSettingsButtonClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToWorktreesButtonClicked(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.Empty>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToWorktreesButtonClicked",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToPartialMessage(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.ClineMessage>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToPartialMessage",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.ClineMessage.fromJSON,
			callbacks,
			options,
		)
	}
	static async initializeWebview(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return UiServiceClient.makeUnaryRequest(
			"initializeWebview",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static subscribeToRelinquishControl(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.Empty>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToRelinquishControl",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
			callbacks,
			options,
		)
	}
	static subscribeToShowWebview(
		request: proto.cline.EmptyRequest,
		callbacks: Callbacks<proto.cline.ShowWebviewEvent>,
		options?: StreamingOptions,
	): () => void {
		return UiServiceClient.makeStreamingRequest(
			"subscribeToShowWebview",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.ShowWebviewEvent.fromJSON,
			callbacks,
			options,
		)
	}
	static async getWebviewHtml(request: proto.cline.EmptyRequest): Promise<proto.cline.String> {
		return UiServiceClient.makeUnaryRequest(
			"getWebviewHtml",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.String.fromJSON,
		)
	}
	static async openUrl(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return UiServiceClient.makeUnaryRequest("openUrl", request, proto.cline.StringRequest.toJSON, proto.cline.Empty.fromJSON)
	}
	static async openWalkthrough(request: proto.cline.EmptyRequest): Promise<proto.cline.Empty> {
		return UiServiceClient.makeUnaryRequest(
			"openWalkthrough",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
	static async trackIntent(request: proto.cline.IntentEvent): Promise<proto.cline.Empty> {
		return UiServiceClient.makeUnaryRequest(
			"trackIntent",
			request,
			proto.cline.IntentEvent.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
}
export class WebServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.WebService"
	static async checkIsImageUrl(request: proto.cline.StringRequest): Promise<proto.cline.IsImageUrl> {
		return WebServiceClient.makeUnaryRequest(
			"checkIsImageUrl",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.IsImageUrl.fromJSON,
		)
	}
	static async fetchOpenGraphData(request: proto.cline.StringRequest): Promise<proto.cline.OpenGraphData> {
		return WebServiceClient.makeUnaryRequest(
			"fetchOpenGraphData",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.OpenGraphData.fromJSON,
		)
	}
	static async openInBrowser(request: proto.cline.StringRequest): Promise<proto.cline.Empty> {
		return WebServiceClient.makeUnaryRequest(
			"openInBrowser",
			request,
			proto.cline.StringRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
}
export class WorktreeServiceClient extends ProtoBusClient {
	static override serviceName: string = "cline.WorktreeService"
	static async listWorktrees(request: proto.cline.EmptyRequest): Promise<proto.cline.WorktreeList> {
		return WorktreeServiceClient.makeUnaryRequest(
			"listWorktrees",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.WorktreeList.fromJSON,
		)
	}
	static async createWorktree(request: proto.cline.CreateWorktreeRequest): Promise<proto.cline.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"createWorktree",
			request,
			proto.cline.CreateWorktreeRequest.toJSON,
			proto.cline.WorktreeResult.fromJSON,
		)
	}
	static async deleteWorktree(request: proto.cline.DeleteWorktreeRequest): Promise<proto.cline.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"deleteWorktree",
			request,
			proto.cline.DeleteWorktreeRequest.toJSON,
			proto.cline.WorktreeResult.fromJSON,
		)
	}
	static async switchWorktree(request: proto.cline.SwitchWorktreeRequest): Promise<proto.cline.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"switchWorktree",
			request,
			proto.cline.SwitchWorktreeRequest.toJSON,
			proto.cline.WorktreeResult.fromJSON,
		)
	}
	static async getAvailableBranches(request: proto.cline.EmptyRequest): Promise<proto.cline.BranchList> {
		return WorktreeServiceClient.makeUnaryRequest(
			"getAvailableBranches",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.BranchList.fromJSON,
		)
	}
	static async getWorktreeDefaults(request: proto.cline.EmptyRequest): Promise<proto.cline.WorktreeDefaults> {
		return WorktreeServiceClient.makeUnaryRequest(
			"getWorktreeDefaults",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.WorktreeDefaults.fromJSON,
		)
	}
	static async getWorktreeIncludeStatus(request: proto.cline.EmptyRequest): Promise<proto.cline.WorktreeIncludeStatus> {
		return WorktreeServiceClient.makeUnaryRequest(
			"getWorktreeIncludeStatus",
			request,
			proto.cline.EmptyRequest.toJSON,
			proto.cline.WorktreeIncludeStatus.fromJSON,
		)
	}
	static async createWorktreeInclude(request: proto.cline.CreateWorktreeIncludeRequest): Promise<proto.cline.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"createWorktreeInclude",
			request,
			proto.cline.CreateWorktreeIncludeRequest.toJSON,
			proto.cline.WorktreeResult.fromJSON,
		)
	}
	static async checkoutBranch(request: proto.cline.CheckoutBranchRequest): Promise<proto.cline.WorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"checkoutBranch",
			request,
			proto.cline.CheckoutBranchRequest.toJSON,
			proto.cline.WorktreeResult.fromJSON,
		)
	}
	static async mergeWorktree(request: proto.cline.MergeWorktreeRequest): Promise<proto.cline.MergeWorktreeResult> {
		return WorktreeServiceClient.makeUnaryRequest(
			"mergeWorktree",
			request,
			proto.cline.MergeWorktreeRequest.toJSON,
			proto.cline.MergeWorktreeResult.fromJSON,
		)
	}
	static async trackWorktreeViewOpened(request: proto.cline.TrackWorktreeViewOpenedRequest): Promise<proto.cline.Empty> {
		return WorktreeServiceClient.makeUnaryRequest(
			"trackWorktreeViewOpened",
			request,
			proto.cline.TrackWorktreeViewOpenedRequest.toJSON,
			proto.cline.Empty.fromJSON,
		)
	}
}
